### ISSUE TITLE
feature request: (cross-platform) services table

### ISSUE THREAD

**Issue by jacknagz** [osquery/osquery#2152]
Per the conversations in the Slack channel earlier, a table for running/installed `services` would be a valuable component into process insight.  Proposed columns:

| `name` | `status` | `pid` |

The equivalent commands for linux and os x are: `service --status-all` and `launchctl list`.

**Comment by arubdesu** [comment]
For Darwin/launchd in specific, these seem like a good start:
- `sessiontype`:  or perhaps another way to refer to it would be 'context' - if started by a LaunchA and therefore without root perms, if in the Aqua context so it's at the login window, etc. Could be too all-encompassing if we wanted to split out the concept of `domain`: since there's a search order that can correspond to the type of job it's controlling (system, local, and if paired with sessiontype it could also include 'user' as options - 'network' should never be in use)  
- `config_path`: where the job's plist was when it was loaded from on-disk (/Sys/Lib, /Lib, ~/Lib, + LaunchA or D directories, as applicable)
- `label`: identifier is always good, unless you're like Puppet and instead of reverse-domain just use crap like 'pxp-agent' ಠ_ಠ
- `program_arguments`: whatever was listed as the options in the launchd plist for the associated key - could be very verbose, would most often probably be joined against file table to look at the script/artifact/binary on disk being called by the launchd job 
 
Those are high-priority to me, but others may want a full dump of the possible options between launchd 1 and 2(10.10+), e.g.:
- `parent`: aka 'manager', process/user/name(meaning associated label) of whatever manages the job
- `run_options`: a whole slew of grab-bag-type options like `KeepAlive` and `RunAtLoad` (which would be bools) and stdout/stderr paths, environment vars, and the rest referred to in the manpage (/usr/share/man/man5/launchd.plist.5) or possibly still current site http://launchd.info (tab two is configuration)

Glad to see more discussion (previously brought up in #1763), things still seem fuzzy to me about whether it needs to be split out in its own table, though. Also not sure how much would prefer to be joined against other tables, so I'm just spouting this initial wish list.

**Comment by arubdesu** [comment]
Upon further review maybe those `run_options`, grab-bag-y options can just be joins/read out with the `preferences` table... not sure if you can always expect launchd to restrict the loading of jobs to specific filesystem paths, though...

**Comment by arubdesu** [comment]
Could we close #1763, which had an old milestone on it, and I'll work on a POC python implementation of this please?

**Comment by directionless** [comment]
Different OSes, and different init systems provide a myriad of options. It's very hard to commit to a single reference for them. However, the `startup_items` is slowly becoming that, especially with #6562
