### ISSUE TITLE
Remote Settings Protocol is not RESTful

### ISSUE THREAD

**Issue by thedrow** [osquery/osquery#2636]
Currently we transmit the enrollment secret as part of the request's body and report authorization errors using the response's body.
We also identify nodes by a "node_key" which is reported during enrollment.
I think we are reinventing the wheel here and it's completely unnecessary.
We can use the OAuth2 protocol for enrollment and the bearer token for node identification.
That way, the protocol will be more easily understood and implemented using known and already implemented mechanisms such as OAuth2 servers. The rest of the protocol can build on top of it using the HTTP statuses defined by OAuth2 to report authorization errors.

The enrollment process will simply be an OAuth2 `client_credentials` grant which will be exchanged for an OAuth2 `Bearer token`.

Moreover, requests should not be retried when the server report 4xx status codes since the server reports the request as invalid for any reason.

**Comment by theopolis** [comment]
Right, originally the remote workflow was designed around our Graph API: https://developers.facebook.com/docs/ When we define nodes on the Graph and associated endpoints it's a bit different than traditional REST. I wont get into the details, but at the end of the day "enrollment" is designed for per-session identifier provisioning.

We tried to make the APIs as universal as possible, and tried to assume others would like different patterns or authentication techniques so we abstracted "enrollment" away from the configuration/logging/etc APIs.

Feel free to write in OAuth2 for enrollment, or try to find creative ways to reuse most of the existing flow to also support a "pure" REST workflow.

**Comment by thedrow** [comment]
So if we want the workflow I proposed I should implement it in a different plugin? One outside of core?

**Comment by theopolis** [comment]
I'd be down with having a `tls_rest_api` flag that added logic to the existing `tls` plugins to make them RESTful. If `--tls_rest_api` is false, they perform as they do now, otherwise they implement a yet-to-be-determined RESTful API.

That's a bit of work:
1. Agree on verbs, inputs, responses, response HTTP codes and document that API.
2. Write all of the conditional logic into the plugins and transport/remote functions. We may have to invent new hand-off-conditionals to support verbs we don't use, or response code retrieval.
3. Write a new mock Python server that demonstrates / tests the added logic.

**Comment by directionless** [comment]
This seems like a request, or speculation, about changing the osquery enrollment protocol. It's pretty stale, I'm going to close it
