### ISSUE TITLE
windows: Mutexes Virtual Table

### ISSUE THREAD

**Issue by cyberallday** [osquery/osquery#2754]
Please add a table for querying Windows mutexes.

**Comment by theopolis** [comment]
This may be helpful: http://pastebin.com/embed_js/zhmJTffK

**Comment by friedbutter** [comment]
We need to be able to join a mutex to process pid. @GJH-OS What columns would you imagine this table should have? I'm thinking we should have at least,` mutex, process, pid`. Anything else you can think of?

**Comment by theopolis** [comment]
I think that's fine. If there's metadata you can get from statting (or similar) that would be cool. A stat usually has the time, which I think is the most important additional field.

**Comment by scottlundgren** [comment]
I have create an entirely uninteresting proof-of-concept on HANDLE enumeration across all processes.  This is done in usermode (no custom kernel module) using a series of reasonably well-known techniques, man of which date back well over a decade.

The proof-of-concept can be found on github at https://github.com/scottlundgren/objects/blob/master/objects/objects/objects.cpp

I have provided example output below.

The proof-of-concept does no filtering by itself - it simply enumerate all HANDLEs across the system, looks up the name associated with the object the HANDLE references, and outputs several interesting fields including the PID, the HANDLE value, the object type number and name (mutex, file, registry key, window station, etc.) and the object name itself (the filename, the mutex name, the registry key name).

By running the proof-of-concept and piping to grep, it is easy to see how the results could be filtered down to just mutexes with a name matching a certain pattern.  

The next step is to implement a proof-of-concept in osquery itself.

**Comment by scottlundgren** [comment]
I updated the sample at https://github.com/scottlundgren/objects/blob/master/objects/objects/objects.cpp so that there are now two logical views:

(1) as stated above, a listing of open HANDLEs on a per-process basis.   This is the output above and includes the underlying object name.  This is analogous to the "HANDLE view" in SysInternals Process Explorer, or the "handle.exe" or "handleex.exe" tools.

(2) new to the example, a listing of named objects within the "BaseNamedObjects" directories within the Windows object namespace.  You can read more about that http://www.nynaeve.net/?p=61 and http://www.nynaeve.net/?p=86, among many other references.

This second logical view is more equivalent to what @theopolis references with his link to  http://pastebin.com/embed_js/zhmJTffK above.  In fact, the implementation in objects.cpp is logically equivalent to what @theopolis references.

In my view, there are actually two related but distinct virtual tables.  First, the per-process HANDLE view with data about the underlying Windows object that the HANDLE references.  Second, the process-agnostic view of the object namespace.

Any feedback let me know.  Since I already have the core implementation complete, I'll try adding both virtual tables.  I think it would make sense for me to open another issue to separate these two tables, and then submit two separate PRs in order to keep these separate.   Any objections or comments I'm all ears!

**Comment by theopolis** [comment]
Wonderful! I agree, two tables makes the most sense.

**Comment by scottlundgren** [comment]
The Open HANDLEs vtable is referenced.  #4403 

My proposal is to rename this ticket to increase the scope somewhat.  Rather than limit to just mutexes, the proposal is to rename from:

Windows: Mutexes Virtual Table

to:

Windows: Named Windows Objects

**Comment by scottlundgren** [comment]
`osquery> select * from basenamedobjects where object_type = 'Mutant' limit 10;
+------------+----------------------------------------------------------------------------------------+-------------+
| session_id | object_name                                                                            | object_type |
+------------+----------------------------------------------------------------------------------------+-------------+
| 0          | SM0:844:120:WilError_01                                                                | Mutant      |
| 0          | C::Users:scott:AppData:Local:Microsoft:Windows:Explorer:iconcache_idx.db!rwWriterMutex | Mutant      |
| 0          | UGTHRSVC_Perf_Library_Lock_PID_aac                                                     | Mutant      |
| 0          | .NET CLR Networking 4.0.0.0_Perf_Library_Lock_PID_aac                                  | Mutant      |
| 0          | SM0:2180:304:WilStaging_02                                                             | Mutant      |
| 0          | TapiSrv_Perf_Library_Lock_PID_aac                                                      | Mutant      |
| 0          | MSDTC Bridge 4.0.0.0_Perf_Library_Lock_PID_aac                                         | Mutant      |
| 0          | SM0:2664:304:WilStaging_02                                                             | Mutant      |
| 0          | SM0:1880:304:WilStaging_02                                                             | Mutant      |
| 0          | SM0:3320:304:WilStaging_02                                                             | Mutant      |
+------------+----------------------------------------------------------------------------------------+-------------+`

**Comment by scottlundgren** [comment]
`
osquery> select * from basenamedobjects where object_type = 'Mutant' limit 10;
+------------+----------------------------------------------------------------------------------------+-------------+
| session_id | object_name                                                                            | object_type |
+------------+----------------------------------------------------------------------------------------+-------------+
| 0          | SM0:844:120:WilError_01                                                                | Mutant      |
| 0          | C::Users:scott:AppData:Local:Microsoft:Windows:Explorer:iconcache_idx.db!rwWriterMutex | Mutant      |
| 0          | UGTHRSVC_Perf_Library_Lock_PID_aac                                                     | Mutant      |
| 0          | .NET CLR Networking 4.0.0.0_Perf_Library_Lock_PID_aac                                  | Mutant      |
| 0          | SM0:2180:304:WilStaging_02                                                             | Mutant      |
| 0          | TapiSrv_Perf_Library_Lock_PID_aac                                                      | Mutant      |
| 0          | MSDTC Bridge 4.0.0.0_Perf_Library_Lock_PID_aac                                         | Mutant      |
| 0          | SM0:2664:304:WilStaging_02                                                             | Mutant      |
| 0          | SM0:1880:304:WilStaging_02                                                             | Mutant      |
| 0          | SM0:3320:304:WilStaging_02                                                             | Mutant      |
+------------+----------------------------------------------------------------------------------------+-------------+`

**Comment by muffins** [comment]
@scottlundgren sounds good! Yeah I think the naming you’ve proposed sounds great, but we can refine that one PR, and two tables also sounds good. Thanks for the updates!

**Comment by scottlundgren** [comment]
pull request (finally) submitted.  The PR description includes a reasonable summary of how this work might fit in the larger picture.

**Comment by scottlundgren** [comment]
in response to questions around the naming of tables, I have written a document at https://docs.google.com/document/d/1BadhBDXMJvFiSq7_raSrGGh54KSq1jw91ANYDSw2xzc/edit#

This docuent, as currently written, proposes two tables to make querying the windows kernel object directory namespace straightforward:

winobj - generic query of a specified directory, similar to how the windows registry is exposed via osquery. This is good for general purpose use cases but not the specific use case of threat-hunting by known windows object name, such as a mutex.

winbno - an unfortunately confusing name, but the best I could come up with. bno stands for "base named objects", which is where Win32 APIs put named objects (such as mutexes) by default. This table exposes all the objects within the (multiple) differing places where they are found within the object namespace and presents them as a simple, easy to use table.

The current implementation in PR #4547 therefore implements (mostly*) the winbo table proposed here.

*why mostly?
In order to complete the implementation, two changes:

change the table name in the spec to be winbno
add code to query the global object namespace and append to the results set. This is not hard.
I am looking for a review of the document itself, as this was one of the feedback items provided by @muffins in the most recent iteration. @zacbrown might also have an interest based on his past participation in the review process.

If the table names and schema and approach seem sound, then I can easily update the PR with new code to reflect.

**Comment by muffins** [comment]
This landed.
