### ISSUE TITLE
windows: provisioning still fails if multiple Python installations exist

### ISSUE THREAD

**Issue by muffins** [osquery/osquery#3959]
our provisioning scripting has issues if Python either already exists on the system, or is not present in the default path. The attempt to install python is fine but adding to our system path is failing.

**Comment by fmanco** [comment]
I did a little debugging on this. Basically the script fails because it assumes after installation it is going to find python and it's path. But because python3 comes first the version found is not the right one and the function returns False which is then written to env.

There are two things here, one is the script shouldn't assume python is going to be found after installation. The second is that since we only support python 2, maybe we should replace invocations of `python` with `python2`. This is also true for building which also fails if python3 comes up first. So maybe we need to change all the python scripts.

What do you think? Feel free to assign this to me if you're not working on it.

**Comment by muffins** [comment]
I think those are great ideas! Note that you can also grab the Python installation path from the system registry, might be a better approach then how I’m doing t now, we simply needed an assurance that we were greater than Python 2.7.12, but the version info might also be in the registry. I’d say go ahead and knock this out if you see the path forward :)

**Comment by mike-myers-tob** [comment]
@muffins I believe the script this issue refers to was removed last month, and this issue can be closed. Can you confirm?

https://github.com/osquery/osquery/commit/dc5e13c3d272f473bffc263299b82c0ab4401aa6

**Comment by muffins** [comment]
yeah @mike-myers-tob that's correct, I'm pretty sure we can close this now.
