### ISSUE TITLE
KEXT table on macOS not showing actual path of artifact

### ISSUE THREAD

**Issue by arubdesu** [osquery/osquery#4275]
```
osquery_version = 3.1.0
     os_version = 10.13.4
       os_build = 17E199
    os_platform = darwin
```
### What have you already tried?
running osqueryi (with or without sudo) with the following query:
```
select name, version, path from kernel_extensions where name not like '%com.apple%';
```
### What did you expect to see?
actual path to kext, as installed, e.g.
   `path = /Library/Extensions/CbOsxSensorProcmon.kext/Contents/PlugIns/cbsystemproxy.kext`
### What did you see instead?
```
   name = com.bit9.cbsystemproxy
version = 1801.24.61fc3
   path = /Library/StagedExtensions/Library/Extensions/CbOsxSensorProcmon.kext/Contents/PlugIns/cbsystemproxy.kext
```

**Comment by obelisk** [comment]
Heyo,

It seems that this is a new feature in macOS high sierra to handle user authorized extensions and that is the entry point for the kernel extension. The kext information in that table is provided by the macOS API call `KextManagerCopyLoadedKextInfo` so we are getting that data directly from the OS...

I found some more information here: https://eclecticlight.co/2018/01/02/the-app-you-cant-trash-how-sip-is-broken-in-high-sierra/

But this seems to be something Apple is doing and may change in the next version of macOS.

**Comment by arubdesu** [comment]
Can we consider re-prioritizing this as a bug? It's functionally teh borked/inaccurate (IMO). As a workflow this blocks being able to run kextload on... unapproved kexts at the path on disk instead of the phantom in the 'waiting room'.
As per @pudquick, this is the probable bug being experienced:
```sh
OSBundlePath - CFString (this is merely a hint stored in the kernel; the kext is not guaranteed to be at this path)
OSBundleExecutablePath - CFString (the absolute path to the executable within the kext bundle; a hint as above)
```
That 'hint' is still  _probably_ helpful to capture, but not what I'm expecting/looking for. Yes, there may be null as the kext is no longer actually on disk, but (again, as per the perennially smarter-than-me @pudquick) this is what I'm _expecting_ will return an accurate path:
https://developer.apple.com/documentation/iokit/1562905-kextmanagercreateurlforbundleide?language=objc

**Comment by pudquick** [comment]
I mean, from an implementation standpoint - "path" is not really a trustable thing in the first place.

With macOS, at least for non-Secure Boot devices, kexts at reboot are generally bootstrapped with the prelinkedkernel which contains all the binary images of the kext - so the content your machine boots up with isn't actually loaded from the "paths", but this file instead.

More information about that structure (and how it can be manipulated ....) here: https://pikeralpha.wordpress.com/2015/07/28/apples-kext-signing-bypassed/

(Secure Boot devices do not actually support a prelinked kernel at boot and _only_ load immutablekernel, which is a static image of Apple-only kexts.

Since the kexts aren't loaded from the files, the path is a bit of a fiction / essentially just recorded metadata, which may or may not be valid anymore, thus the label "a hint".

Possibly the best thing we can do here is maybe expose both things? Maybe both OSBundlePath as path and KextManagerCreateURLForBundleIdentifier as "current_path" or something.

**Comment by arubdesu** [comment]
As kexts become increasingly de-emphasized/deprecated/frameworks are blocked from loading, and this is all put into a cache that the system inflexibly manages/controls, it becomes both harder to deal with and more relatively arcane. As it doesn't seem others have been clamoring for this additional/ visibility I can let this close.
