### ISSUE TITLE
For Discussion: Discovery queries run before extensions autoload

### ISSUE THREAD

**Issue by jkeljo** [osquery/osquery#4302]
I have some queries that are gated by discovery queries that rely upon extension tables. I've seen them take a while to actually start running because the first run of the discovery query happens before the extension is loaded, fails due to the table being missing, and then it is not run again until the pack refresh interval has passed.

What's the intended fix here? Make the extension required instead of autoload? Decrease pack refresh interval? Change osquery to re-run failed discovery queries after extensions load, just in case? Something else?

**Comment by Smjert** [comment]
For posterity: if an extension is vital (normally because it's a config or logging extension), or if you simply want to ensure that it's present before anything else happens, you should be using `--extensions_require` with the extension name/id.
This can be used in conjunction with `--extensions_autoload`.
