### ISSUE TITLE
windows event ID's - Subscriber table missing

### ISSUE THREAD

**Issue by gnomefish** [osquery/osquery#4772]
### What version of `osquery` are you using? What operating system. Be specific.

3.2.9-106-g1046757c

### What have you already tried?

osqueryi --disable_events=false --windows_event_channels="System,Application,Setup,Security"
osquery> select * from windows_events where eventid = 4672;

### What did you expect to see?

the actual windows event ID's matching 4672

### What did you see instead?

E0729 09:23:56.289115  3628 additional_amalgamation.cpp:2141] Subscriber table missing

**Comment by gnomefish** [comment]
when running it with a different flag (--nodisable_events) it works... strange:

osqueryi --verbose --nodisable_events --windows_event_channels="System,Application,Setup,Security” --logger_plugin=filesystem --events_max=50000

select time, eventid, source, data from windows_events where eventid = 4658 limit 1;

**Comment by muffins** [comment]
@gnomefish can you show us the results of `select * from osquery_flags where name = 'windows_event_channels'`? Also, the Windows events table only grabs events going _forward_ in time, so you'll need to generate those events _after_ you've dropped to the osquery shell, once new events are triggered, you can query the table and you should see them

**Comment by Smjert** [comment]
The event framework recently got a rework, especially around Windows events.
Testing a bit in general I can see events fine and also select them via `eventid`; since this is using an old osquery version and there haven't been an answer for a while, I'll close.
Feel free to reopen if the issue is still present with the latest version of osquery.
