### ISSUE TITLE
[blueprint] Use JSON number syntax for columns data in logger

### ISSUE THREAD

**Issue by j-calvert** [osquery/osquery#4799]
Currently, loggers treat all data from sqlite query results as text.  Sometimes consumers have to determine if the data is text or number, and if a number, sometimes they also have to determine if it's a integer/long or float/double.

This can be "encoded" within the JSON representation of the data, and the proposal here is to do just that.

Consider **NULL, INTEGER, FLOAT, TEXT, BLOB** as used in [sqlite's API](https://www.sqlite.org/c3ref/column_blob.html) and **string, chars, char, number, int, frac, exp, digits, e** as used in [the JSON syntax spec](https://www.json.org/).

Currently osquery loggers use a method which internally requests everything as a string.

For **NULL**s, this results in a nullptr and we omit it from the resulting JSON object.  We'll retain this behavior.

For **BLOB**s, this results in adding a \0 terminator is needed and representing it as a JSON **string**.  We'll retain this behavior.

For **TEXT**s, we'll maintain it's represntation as a JSON **string**.

For **INTEGER**s, we'll introduce a change such that the JSON that's produced conforms to the **int** or **int exp** portion of the spec rather than **string**.

For **FLOAT**s, we'll introduce a change such that the JSON that's produced conforms to the **int frac** or **int frac exp** portion of the spec rather than **string**.

There's some nuance to how the type of a column is determined, particularly for complex queries where, say, types from subqueries are implicitly and/or explicitly cast to form an end result.

For this change, the current plan (subject to discussion) is to employ [getQueryColumnsInternal](https://github.com/facebook/osquery/blob/master/osquery/sql/sqlite_util.cpp#L499), a method that's used by some log consumers.  For, eg, TLS loggers, these consumers may be running on different platforms, which introduces problems and non-parity, e.g. around extension tables that exist on the log-producing platform, but not the log-consuming platform.  This change will help such consumers stop having to do their own type determination.

However, since we'll now be doing type determination at the same time we're obtaining the data, it might be non-optimal (and non-necessary) to do the query analysis that getQueryColumnsInternal does.

So, on one hand, we'd be doing smaller, more isolated changes by moving calls to getQueryColumnsInternal from log consumer to log producer, and only after this is complete, reconsidering how we do column type determination.

On the other hand, we may non-trivially impact the performance of osqueryd in the interim.

I'm interested in people's opinions on one approach vs. the other.

If we can get behavior parity with getQueryColumnsInternal without QueryPlanner, the second option is more attractive.  To this end, I'd be grateful to hear from anybody that has some sql (ideally self-contained...so including table creation if needed) where getQueryColumnsInternal gets the type of a returned value correct, but not so for any reasonable heuristic using **[sqlite3_column_decltype](https://www.sqlite.org/c3ref/column_decltype.html)** and **sqlite3_column_type**.

Thanks!

**Comment by fmanco** [comment]
I really like this proposal. Having json serialized with proper types would make things much easier consuming the data upstream.

Regarding the use of `getQueryColumnsInternal()` are you talking about using that directly or reusing some of the code? I think we had discussed previously replacing the use of `sqlite3_exec()` with it's lower-level components and then make use of `sqlite3_column_type()` to do the type determination, which I think is what you're suggesting and with which I agree. For the cases for which `sqlite3_column_type()` wouldn't work we could make use of the query planner based alternative or last resort even try to "manually" try cast the values, since despite being much more expensive I suppose it doesn't happen very often.

Regarding how you transport the properly typed results to the loggers, how do you plan to do it? Replacing `QueryData` with a different type?

In general this makes a lot of sense. Maybe if you start submitting some ideas as PRs, even incomplete, it would help make things more clear, and understand the issues better.

**Comment by j-calvert** [comment]
You're correct, when we last talked I was thinking about replacing out use of `sqlite3_exec()`, eliminating our use of query planner, and putting the type info into `QueryData`.

But, I've since decided against moving away from `sqlite3_exec()`.  The code comments for it say that it's a wrapper for other available APIs, but that didn't turn out to be true.  Also, it's not actually necessary to do this for the task at hand.

Replacing `QueryData` in a way that doesn't involve a massive refactor (a lot of which would be code that has nothing to do with osqueryd loggers) seemed a lot more difficult than necessary, as well (investigation into boost::invariant notwithstanding).  Instead, we can get what we want with a more localized change by passing the type information around separately as a map of columnName-->type, where if the column is not present in the map, we default to existing behavior.

Finally, I do still intend to attempt replacing use of query planner with calls to `sqlite3_column_type()` and `sqlite3_column_decltype()`, but in the interest of making multiple, smaller, incremental changes, I'm just having osqueryd call `getQueryColumnsInternal()` for the [current, proposed initial change](https://github.com/facebook/osquery/pull/4827).

I still should verify, as we discussed, that our tailer will accept numeric values within the columns object.  At the same time, it is valid JSON (within JSON that already has numerics, eg `"unixTime":1532980590,"epoch":0,"counter":0`, at the same level as the columns object), so this should be mostly a formality/sanity-check.

**Comment by fmanco** [comment]
According to the point 5 of [this doc](https://www.sqlite.org/cintro.html) `sqlite3_exec()` is a wrapper around core functions. Actually the shell doesn't directly use `sqlite3_exec()` but reimplements it with [shell_exec](https://github.com/facebook/osquery/blob/master/osquery/devtools/shell.cpp#L798-L931). What did you find that prevents you from replacing `sqlite3_exec()`.

Changing `QueryData` requires a big refactor given it's used by all the tables. But what about introducing a new type, something like `QueryDataTyped` which would only be used after the execution. Would that be harder than adding the new argument to keep the column types?

Finally, I have two concerns with your initial approach on #4828. The first is performance, we're discarding the types during query execution and converting all values to strings, just to then recalculate the types and convert everything back. For an int value for example the full pipeline would be `int -> string -> int -> string -> int` this approach makes it worse by adding yet another cast and I would love if it could make it better by removing one cast. The second one is that according to documentation you actually cannot know the types of the columns outside of query execution and they can actually change from row to row, because of the following comment on the [docs](https://www.sqlite.org/c3ref/column_decltype.html):

> SQLite uses dynamic run-time typing. So just because a column is declared to contain a particular type does not mean that the data stored in that column is of the declared type. SQLite is strongly typed, but the typing is dynamic not static. Type is associated with individual values, not with the containers used to hold those values.

Let me know your thoughts.

**Comment by guliashvili** [comment]
This is very good and long-awaited feature, so we should definitely implement it somehow. getQueryColumnsInternal is not just the way to go, as we might stop supporting it. Actually, I hope will be able to remove it in the near future(at least the explain parser). I looked at the sqlite3_exec source and it's quite straightforward to replicate and add type support. I will be more than happy to support your work and do smaller tasks to make implementing this feature possible.

**Comment by j-calvert** [comment]
Re: using sqlite3_exec, my initial inclination was to do what's suggested, but when I saw that sqlite3_exec was, internally, using several non-public methods, I figured that the "point 5" to which Filipe refers was dated.  On reconsideration, point 5 says that sqlite3_exec is doing the 4 steps that **can** be (not are) done with the 4 public methods.  I'd guess that the non-use of the public methods is to marginally optimize sqlite3_exec...or something.  In any case, the code that Filipe points to is a clear example of how this we're actually already doing this (thanks for that), and I'm happy to go that route...and now that we're going that route, it makes all the more sense to also not use getQueryColumnsInternal.
  
Re: new QueryDataTyped object vs. an optionally-empty map of column types:  My diff shows the extent of the latter approach, primarily adding an empty map literal to a couple dozen method calls, and passing an actual map of column to type in the only places where we want to serialize numbers as numbers.  

If I understand the QueryDataTyped approach, it would be to add this new "typed" map, and replace all uses of it in the "in-process" path of sqlite-query to JSON-serialization, namely for logging and storing in our the local DB.  So, DiffResults, QueryLogItem and other uses of QueryData in query.h would be changed to use QueryDataTyped.  Meanwhile, the use of QueryData in the thrift interface used by extensions would remain as-is.  Does that sound right?  Hoping it does, that approach sounds good to me...

Now, if QueryDataTyped is nothing more than a structure of data that we've retrieved via sqlite APIs and want to pass along to something that's going to serialize it as JSON via a rapidjson writer, is there any reason not to just have our QueryDataTyped be a rapidjson::Value?  Filipe and I chatted about using boost::variant, but that was when we were considering implications of modifying QueryData rather than partially replacing use of it.

Thanks for the help!

**Comment by fmanco** [comment]
Regarding your last point. Theoretically we should be able to serialize into multiple formats (e.g. xml). We're not doing that now, but using something like boost variant instead of json values would simplify that in the future.

**Comment by guliashvili** [comment]
@j-calvert I had to check sqlite3_exec implementation, looks like there are no any optimizations done, using internal functions, it's just the 
> convenience wrapper 
( It's called like that in the docs)

**Comment by j-calvert** [comment]
How is boost::variant --> XML easier than JSON --> XML?

Will that make have made it worthwhile for us to have gone from sqlite-->boost::variant-->JSON instead of sqlite-->JSON?

**Comment by guliashvili** [comment]
I think, we'd rather prefer to use variant and not to get attached to the rapid json type, for several reasons. I expect boost type, to be better maintained, also in the next version of C++ we  can even switch to the STL variant. In case if we switch to other format(xml does not looks realistic, but something more compact does), it's weird to keep rapid json statically linked to the osquery, just because we use it's type as the main encapsulation method internally.

**Comment by j-calvert** [comment]
Quick summary for August.  Please update/comment if/as you see fit.

We're going the sqlite-->boost::variant-->JSON route.

[PR 4904](https://github.com/facebook/osquery/pull/4904) is mostly on target, with the biggest outstanding request being addition of an opt-out flag.

It's currently being broken up into smaller PRs, starting with [PR 5114](https://github.com/facebook/osquery/pull/5114)

**Comment by directionless** [comment]
I'm not sure what the state of this is, but I'm going to close this as stale
