### ISSUE TITLE
Remove dependency on ptree-based `parseJSON()` from `firefox_addons` table

### ISSUE THREAD

**Issue by fmanco** [osquery/osquery#4902]
# Task

Remove `firefox_addons` table [dependency](https://github.com/facebook/osquery/blob/master/osquery/tables/applications/posix/browser_firefox.cpp#L59) on ptree based [parseJSON()](https://github.com/facebook/osquery/blob/master/include/osquery/filesystem.h#L278).

Afterwards remove the `parseJSON()` and related. One more step to remove the `ptree` dependency.

**Comment by mike-myers-tob** [comment]
Is there a high-level goal of removing the third-party dependency `ptree`? If so, there are many more tables where it is used. We should have an issue that tracks the removal of all of them.

Secondly, what is the preferred alternative for JSON parsing? RapidJSON? Because we are also using that throughout.

Related: https://github.com/osquery/osquery/issues/4357

**Comment by theopolis** [comment]
> Is there a high-level goal of removing the third-party dependency ptree?

Nope, the goal of porting anything from `ptree` to `RapidJSON` is performance improvement. The ptree implementations are a lot slower. It was important for us to port anything in the core/common of osquery but the individual tables are less of a priority. Because of this you'll see several of these "porting" PRs completed a long time ago.

At the end of the day I don't think we'll be able to ever completely remove `ptree` due to it being used within other boost libraries. This is a guess but it influences: we shouldn't be focused on removing the code.

**Comment by mike-myers-tob** [comment]
Sounds like, although this might improve performance of JSON parsing, that performance in the `firefox_addons` is not a priority or a problem currently.
