### ISSUE TITLE
Distributed queries execute regardless of discovery

### ISSUE THREAD

**Issue by packetzero** [osquery/osquery#5260]
# Bug report

According to the documentation, "If all of the discovery queries return more than zero rows, then the queries are added to the query schedule".  However, the code in distributed.cpp acceptWork() will add queries regardless of the discovery scan results.

### What operating system and version are you using?

The bug is cross platform. I'm on MacOS X 10.13.6

### What version of osquery are you using?

version = 3.3.1-32-g28ffde72

### What steps did you take to reproduce the issue?

Use a distributed setup with a discovery query.  For example, the following 1_1 query should never run, since the discovery 'past' query will not return any rows

`{"discovery":{"past":"SELECT * from time where year=1902;"}, "queries":{"1_1":"SELECT * FROM osquery_info;"}}`

### What did you expect to see?

The response from the above request should be:

`{"queries":{"1_1":[]},"statuses":{"1_1":0}}`

### What did you see instead?

The result for queries '1_1' will be populated.

**Comment by directionless** [comment]
Hrm. I can't find docs about how discovery queries and distributed queries are supposed to interact. But I did stare at the code a bunch... I don't know what correct is here, but it looks like the behavior as written expects the discovery query to be named the same as the query. Eg: there's a 1:1 map between them. So you'd want 
```
{"discovery":{"1_1":"SELECT * from time where year=1902;"}, "queries":{"1_1":"SELECT * FROM osquery_info;"}}
```
_But_ I think the logic is wrong anyhow. If _all_ the discovery queries have no results, then `queries_to_run` remains empty, and all the distributed queries succeed.

So, if I read this correctly, you can get the desired behavior via:
```json
{"discovery":{
   "bogus":"SELECT 1;",
   "1_1":"SELECT * from time where year=1902;"
}, 
"queries":{"1_1":"SELECT * FROM osquery_info;"}}
```

Of course, this is terrible. The underlying logic shouldn't be that hard to fix. Only I don't know what it _should_ be. I tend to think the syntax should match that of packs -- discovery queries is an array, not a map. But that is potentially an API change.

**Comment by theopolis** [comment]
> Of course, this is terrible.

Agreed, we should revisit the documentation, expectation, and implementation here.

**Comment by np5** [comment]
+1

Also: [examples](https://github.com/osquery/osquery/blob/1699adc38741c05bd9cf02fe6995a9aca9de9504/tools/tests/test_http_server.py#L87-L98) in the test http servers show the functionality being used to restrict the queries to some platforms. Maybe the packs scoping via discovery (as list of queries)/platform/version could be used for the distributed queries too.

**Comment by lucasmrod** [comment]
Hi folks.

Fleet currently makes use of "distributed discovery queries" for avoiding the "no such table" errors with some extension tables, see [here](https://github.com/fleetdm/fleet/blob/15de4f3e65883abbb08ead57102e40f2fcac809c/server/service/osquery_utils/queries.go#L360-L363).
At the time, we decided to use the undocumented feature because it is useful to Fleet and the code/logic hasn't change in ~5 years.

We attempted to explain the undocumented "distributed discovery" implementation [here](https://github.com/fleetdm/fleet/blob/9d01ba33c6e5f85bc5fb8c3dc61c5b875193a5de/server/service/osquery.go#L575-L587), and is also documented by `osquery-go` [here](https://github.com/osquery/osquery-go/blob/df1df42c82067c127a136c13406a32eeb9e3e7da/plugin/distributed/distributed.go#L21-L26). In order to use the feature Fleet has to set a `SELECT 1;` query for the queries that do not need a discovery query.

Putting the odd logic/behavior aside, the bug as mentioned in this issue is that all queries are executed if:
- `discovery` queries are present, and,
- all discovery queries return no rows.

In #7655, I propose a simple fix for this bug without changing the odd behavior/logic (+ it adds some tests to `acceptWork`).

I'm open to discuss changing the behavior on another issue (maybe not requiring all queries to have a discovery query would make more sense). This would avoid having to send `SELECT 1;` on the queries that should run no matter what.

**Comment by directionless** [comment]
Hi @lucasmrod, thank you so much for taking a pass here.

I am not sure that this is the correct solution, but I'm willing to hear more.

I think there are maybe two points to discuss. The first is whether or not we should keep distributed discovery queries so dramatically different than scheduled queries. And the second is whether to require the `SELECT 1`.

As for the first, I feel very unsure. One of the things I find hardest about osquery, is that it feels like we have very little consistency. Discovery queries here, are completely different than on schedules. Etc. That sort of skew is a huge mental toll. So, somewhat, I favor making this more consistent -- discovery queries should be an array. Counterpoint -- I really wish discovery queries could be query-level, and not just pack level. And this may be the only way to get query level discovery queries on distributed queries. So maybe it's fine to double down on this, and maybe we can fix it in some hypothetical future API.

As for the second, I think if we embrace the discovery-queries-as-a-hash, I think we should not require `SELECT 1`. That feels like an API bug. If the query is not present in the hash, then we **should** execute it.

There's maybe some side question as well -- scheduled discovery queries allow one to have multiple discover queries. In a hash, I'm not sure how we can easily support that. (we could introspect the json response, but that's hard in go)

**Comment by lucasmrod** [comment]
> I think there are maybe two points to discuss. The first is whether or not we should keep distributed discovery queries so dramatically different than scheduled queries. And the second is whether to require the SELECT 1.
As for the first, I feel very unsure. One of the things I find hardest about osquery, is that it feels like we have very little consistency. Discovery queries here, are completely different than on schedules. Etc. That sort of skew is a huge mental toll. So, somewhat, I favor making this more consistent -- discovery queries should be an array. Counterpoint -- I really wish discovery queries could be query-level, and not just pack level. And this may be the only way to get query level discovery queries on distributed queries. So maybe it's fine to double down on this, and maybe we can fix it in some hypothetical future API.

I agree with your points here. Some consistency between features would be cool, but at the same time query-level discoveries is a useful feature in distributed queries.

> As for the second, I think if we embrace the discovery-queries-as-a-hash, I think we should not require SELECT 1. That feels like an API bug. If the query is not present in the hash, then we should execute it.

Agree on this one too, Fleet sets `SELECT 1;` on the queries that don't require a discovery query.
The logic should instead be that if there's no discovery query for a query then it should just run.
(The PR linked to this issue just fixes a corner-case bug, IMO this logic should be changed on a separate issue/PR.)

> There's maybe some side question as well -- scheduled discovery queries allow one to have multiple discover queries. In a hash, I'm not sure how we can easily support that. (we could introspect the json response, but that's hard in go)

This could be supported by defining the values of the discovery hash as an array of queries instead of a single query string.
But that would require either a breaking change in the API or a new `discovery2` field. Not sure how requested such feature is.
