### ISSUE TITLE
Kafka & SSL support for osquery on Windows

### ISSUE THREAD

**Issue by meyerjom** [osquery/osquery#5678]
# Feature request 
Hello everyone, 
I would like to use Osquery on a larger scale and would need a Apache Kafka producer for the Osquery windows client. Important for me would be an SSL-encrypted and authenticated transmission into a Kafka-topic.

Are there any current plans for version 4 to introduce these features? 
If not, what difficulties & problems are to be expected? 

### What new feature do you want?
- Output to Kafka. SSL-encrypted and authenticated.

### How is this new feature useful?
- Opens the possibilty to use a highly scalable Kafka-based event-bus. 

### How can this be implemented?
- I don't know. At the moment I want to understand why this feature doesn't exist and which difficulties could arise. I am happy to receive implementation tips.

**Comment by flappy-sh** [comment]
Hello, right now we are trying to build osquery with kafka on windows , and we find some issues with the missing librdkfka.dll file (windows dependencies) .  What solution you propose so that the librdkafka code is more "presentable" in the repo @Smjert ? .

**Comment by Smjert** [comment]
Hello @flappy-sh, the current supported way is to build the libraries from source and produce a static library which is then linked with the rest.
Since the library source code is already present in our repositories (built here https://github.com/osquery/osquery/blob/master/libraries/cmake/source/librdkafka/CMakeLists.txt), the idea is to "port" it to Windows.

To do that you have to write some CMake code, the important bits are:
1) There's a list of libraries and platforms where they should be searched on, if missing. You should add Windows
https://github.com/osquery/osquery/blob/8e6fefb47ad2ae08f11f480e890ce991835ae7a6/CMakeLists.txt#L88-L126

2) We have the concept of layers for libraries, which means that when searching for a library, the CMake code will look layer by layer in the order they have been listed, and stop as soon as the search is satisfied.
Layers correspond to folders under `libraries/cmake`.
What we have now is shown here: https://github.com/osquery/osquery/blob/8e6fefb47ad2ae08f11f480e890ce991835ae7a6/cmake/options.cmake#L81-L87

3) The search is performed through the use of `find_package` and custom CMake modules; the modules you're interested in are defined under `libraries/cmake/source/modules`.
The idea with Windows (and macOS) though is that we have a temporary layer, which is `source_migration`, which defines its own modules of the libraries that have been ported, so that the ones that aren't will fallback using Facebook pre-built libraries.
These modules are all basically one liners because they actually include the ones from the source layer.

4) In the end, most likely the following CMakeLists.txt will have to be updated to support Windows https://github.com/osquery/osquery/blob/master/libraries/cmake/source/librdkafka/CMakeLists.txt

In general you can find past examples in the commits on how we ported libraries.
Some do not require any change to the CMakeLists.txt that builds them, so it's only a matter to inform CMake to search for it and where it is; in other cases you need to change that too.

**Comment by flappy-sh** [comment]
Hello @Smjert  , the instructions were very usefull , im stuck at a linkage error right now but i hope i can push to a branch tomorrow .

**Comment by flappy-sh** [comment]
a small branch enabling the kafka build on windows https://github.com/flappy-sh/osquery/commit/92ca73f97ab4316ca4889ef9ea78ac51badd5a58#

**Comment by mike-myers-tob** [comment]
Did PR #6095 resolve this? Can we close the issue?

**Comment by Smjert** [comment]
https://github.com/osquery/osquery/pull/6454 was also needed to correctly link the library on Window; closing since this has been implemented.
