### ISSUE TITLE
build / package / sign pipeline

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5689]
This is meant as an initial place to discuss a future osquery build / package / sign pipeline. The high level things have come up a couple of times

cc: @groob @Smjert @alessandrogario @directionless

**Comment by directionless** [comment]
I would generally propose splitting these up into separately managed processes. This gets us better tooling separation as well as better permissions management. Here's my initial proposal...

## Build

Build is a dedicated pipeline. This looks a lot like the CI things today. Builds happen, and the resultant binaries land in some artifact storage. (s3, gcs, whatever)

An important point here is that the binaries are easy to work with. A predictable download path, and format. 

Recommend we use the existing `cmake` for this

## Packaging

Packaging is its own process. It should take binaries from the build artifacts, and produce packages. This is likely a different process per package format.

My bias is to look at re-using the packaging tooling I wrote for [launcher](https://github.com/kolide/launcher/) for this. If people are okay with go, I'm willing to take that on.

## Signing

Signing is a bit thornier. On one hand, it's very much it's own process. _But_ it also needs to be linked with the others.

### Key management 

Ideally our keys are stored in a cloud KMS (or HSM). But, not all the tools support this. So there's some work and compromises.

**Comment by packetzero** [comment]
Might need two separate sign steps.  One for binaries, one for signing package.

**Comment by theopolis** [comment]
I can volunteer to create the needed AWS creds so the CI can publish to `osquery-packages`. The build artifacts can be published here as well as the signed packages.

If we find a KMS that allows importing I can import the existing GPG keys used to sign. I am also unsure how to handle macOS signing.

**Comment by mike-myers-tob** [comment]
Regarding Packaging, above:

> take binaries from the build artifacts, and produce packages. This is likely a different process per package format.
>
>My bias is to look at re-using the packaging tooling I wrote for launcher for this. If people are okay with go, I'm willing to take that on.

I'm inclined to welcome code that is already written and tested, _however_ there are some concerns after talking with the team here:

- Trail of Bits would like to use an existing standard build tool like CPack for as much as it can be used for: it will require less maintenance in the long run.
- we want a clear boundary between vendor-neutral osquery core and vendor-specific packaging/deployment code.
- can the Kolide packaging code be reused without adding an external (Kolide) dependency?
- adding Go-lang code to the build process means another skillset needed to maintain (it's already a mix of Python, CMake, Buck, shell scripts, Azure Pipelines config, etc.). We would prefer to rely on C++ build and package tools for a C++ codebase. If CPack is not well understood, perhaps we can improve the developer documentation.

Honest question: how does CPack compare to the alternatives, regarding our requirements?

**Comment by directionless** [comment]
@mike-myers-tob (and the rest of Tob) I share those concerns 100%. My preference is _also_ for a common, well understand, framework to handle packaging. I would be overjoyed if there was a reasonable that didn't require people to use strange code, or learn new languages. It's not clear to me that `cpack` fits that bill.

The `cpack` model seems to be that we set a bunch of cpack variables, and then pass off to an opaque system. Eg: [packaging.cmake#L305](https://github.com/osquery/osquery/blob/f4bd3e1630b149b5f18db00a5d1f2361636ecc9c/cmake/packaging.cmake#L305). I find that works as long as our needs match exactly what cpack supports, and the code to set those options is not terribly cumbersome.

I'm not sure those conditions hold.

Consider https://github.com/osquery/osquery/issues/5796. I don't understand how that happened, nor do I understand how that's fixed. Nor do I understand how to debug it. There is no simple top-down code for me to read to understand what cpack did to create that. The best I can find is that there was a cpack bug, or maybe we're supposed to run a chown ourselves. 

Consider apple package signing. Right now, I think I have a fairly good understanding of these pieces _as apple envisions them_. But, I have no idea how the cpack authors understand them, and given the dearth of discussion about cpack and notarization, I'm skeptical that anyone else is doing that.

Even just the documentation is hard for me to track. I get that it's all done with sorta magical seeming variables. But where's the list of these? For osx packaging, I can eventually find:
* https://cmake.org/cmake/help/latest/module/CPack.html
* https://cmake.org/cmake/help/latest/cpack_gen/packagemaker.html
* https://cmake.org/cmake/help/latest/cpack_gen/bundle.html
But it's not clear to me whether we're using bundle or packagemaker. 

-----

Regardless of the tooling, this issues is more about the overall pipeline. My experience is that with a reasonable pipeline, it's easy to change and adapt tools. That's a lot harder when there's a monolith.

This is promoted because one thing I really want, is a plain zip/tar distribution for our platforms. As a vendor (and as a former end user) I want the osquery distributed binaries. But I want to make my own packages of them. How can we split the build from the packaging?

**Comment by directionless** [comment]
All that said. if our status quo is working well enough, I'm not going topush a new packaging system through.

**Comment by mike-myers-tob** [comment]
> The cpack model seems to be that we set a bunch of cpack variables, and then pass off to an opaque system.

Yea, my understanding is that it is like invoking a command-line tool with a lot of arguments. The trouble with CLI is researching whether it has an argument for the thing you need. Maybe we (Trail of Bits) can document the the high-level structure, the build phases, and important places where build (and packaging) configuration options lie. If we document for new osquery developers, it won't be such a black box.

Tagging @Smjert to fact-check me on this response comment. Here we go.

> I don't understand how that happened, nor do I understand how that's fixed. Nor do I understand how to debug it. There is no simple top-down code for me to read to understand what cpack did to create that. 

I share this frustration with any set of steps in which there is a hierarchy of dependencies and variable substitutions instead of a linear (at the high-level) point-A to point-B set of steps. It seems like CMake recognizes this too, and there's a toggle for tracing the setting of variables:

- https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#property-origin-debugging
- https://cmake.org/cmake/help/latest/variable/CMAKE_DEBUG_TARGET_PROPERTIES.html

As well as more general debug output and trace modes in CPack:

- foo
- bar

My first intuition is that you'd examine [the commands in the CMake script that specify the file(s) to be installed](https://github.com/osquery/osquery/blob/master/cmake/packaging.cmake#L131): `install(TARGETS`, `install(FILES`, `install(PROGRAMS`. These, apparently, are also the instructions to CPack on [what to package and how (including permissions to set)](https://cmake.org/cmake/help/v3.5/command/install.html#installing-files). This is where I would begin to look for the reason for #5796.

Then, my understanding is that CPack `Generators` invoke system tools to create specific package formats, like a `DEB` Debian package. I am generally unfamiliar with Debian packages and what they contain, so I'd also have to start from the Debian documentation to find the name of the attribute that _should_ be getting set, so I know if CPack is doing what it is supposed to, and clue me into what I want to to add to the CMake script. 

[The page about the CPack DEB Generator](https://cmake.org/cmake/help/latest/cpack_gen/deb.html) documents the list of CPack DEB generator specific variables, which all begin with `CPACK_DEBIAN_`. I believe they are [set here](https://github.com/osquery/osquery/blob/65aca42e5f7f7dadb7fc426a81d2bd80d1305795/cmake/packaging.cmake#L269) in osquery's CMake script.

The Generator seems to be a simple proxy to invoke the native `dpkg_*` tools on the system. The CPack DEB Generator appears to create a ['control file'](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-binarycontrolfiles) for use by the native Debian package utility. [In the osquery CMake file here](https://github.com/osquery/osquery/blob/57f99164730b03903045a0b0179ecf9154f3e943/cmake/CPackConfig.cmake.in#L27), we seem to be pointing to the location of that control file. Maybe this is also a place to examine? 

As a last resort, I see that there's also [a post-install script](https://github.com/osquery/osquery/blob/master/tools/deployment/linux_postinstall.sh) invoked by the Debian package installer, maybe _that_ could set the necessary file permissions on the installed files. But my intuition is that it ought to be possible using the CPack/CMake statements.

> one thing I really want, is a plain zip/tar distribution for our platforms. As a vendor (and as a former end user) I want the osquery distributed binaries. But I want to make my own packages of them. How can we split the build from the packaging?

Maybe I misunderstand, but, through the use of CMake 'targets' I thought it is already possible to build with or without unit tests, with or without packaging, etc? Assuming you know the location of where the artifacts are built, isn't it straightforward to run a zip/tar command to pull all of the files you want into one file? Or, the zip step could be its own CMake target. There is a [CPack Archive Generator](https://cmake.org/cmake/help/latest/cpack_gen/archive.html) that could be invoked.

> For osx packaging, I can eventually find:
>
> https://cmake.org/cmake/help/latest/module/CPack.html
> https://cmake.org/cmake/help/latest/cpack_gen/packagemaker.html
> https://cmake.org/cmake/help/latest/cpack_gen/bundle.html
> But it's not clear to me whether we're using bundle or packagemaker.

The `packagemaker` Generator has been deprecated, so I believe [`productbuild`](https://cmake.org/cmake/help/latest/cpack_gen/productbuild.html#cpack_gen:CPack%20productbuild%20Generator) is the preferred CPack Generator for macOS now. I don't think we're going to deliver osquery as [an `.app` bundle](https://en.wikipedia.org/wiki/Bundle_(macOS)#macOS_application_bundles) in the foreseeable future, so I would ignore that generator. For signing, the documentation for `productbuild` mentions various `CPACK_PRODUCTBUILD_` variables related to signing. Notarization can't be done locally since it's a submit-your-stuff-to-Apple process, so this is where maybe the CI needs to get involved, or else maybe it's a manual step for us.

**Comment by theopolis** [comment]
I think CPack almost gets it correct. I am worried about https://github.com/osquery/osquery/pull/5777 which will require some post-package fixups or a patch to CPack. CPack has a bug when building non-component `productbuild` packages. I imagine we can hack around this with a `make macos_package` that sets a dependency on the `package` target then runs another `productbuild` command to remove the unwanted folder or alter the `package_id`.

If I could edit CPack code I would expose the `package_id` argument as a configurable option.

There are some nice-to-have missing things in the other packages builders like missing some metadata fields. These are not blockers and with more investigation they might be solvable.

**Comment by theopolis** [comment]
The legacy package building approach uses bash scripts in `./tools/deployment` and `fpm`. These work, are easy to debug, allow for more customization (a person can bundle in a config/cert store), and would work well with a `make DESTDIR=/path/to/package install` CMake approach.

If I had a vote I would vote to fix up the bash-script approach and continue using that. We could make it very user-friendly with a `make packages` target that facilitated setting up a directory within `/your/build` as DESTDIR and then running the scripts similar to the old CMake target logic.

**Comment by theopolis** [comment]
I'm trying to make CPack work and running into more issues. I cannot find a way to build `-dbg` versions of DEB. 

1. The non-component `.ddeb` generation is broken and there is a fix in progress here: https://gitlab.kitware.com/cmake/cmake/merge_requests/3837/diffs
2. Switching to a component-based install almost works but CPackDeb is looking at the installed versions of ELFs for a list of files to provide symbols for https://gitlab.kitware.com/andrew/cmake/blob/d8a3939aef44f6176ac3ec03fb8cdd396fa96ca3/Modules/Internal/CPack/CPackDeb.cmake#L122 this is the wrong approach as the installed-version will already be stripped via `CPACK_STRIP_FILES`. 
3. DEB generation does not set a `License` https://github.com/Kitware/CMake/blob/master/Source/CPack/cmCPackDebGenerator.cxx#L670 (nitpick)

A potential work around for (2) is to create a new component called `dbg` and replicated the logic in `./tools/deployment/make_linux_package.sh` to set up a structure for the debug package. Before I begin trialing this I want to get folks opinions.

I had tried building a `-debuginfo` RPM and there are other oddities in CPack that we will have to work around. I suspect we'll need to take the same route at with DEB generation and create a debug component.

**Comment by theopolis** [comment]
My current feeling is that to achieve what we had before with CPack we have to "pile on" several workarounds.

I'd rather set up an API for the three `./tools/deployment/make_$PLATFORM_package` scripts and call them from CMake: `SCRIPT ${CMAKE_BINARY_PATH} ${CMAKE_SOURCE_PATH} ${DESTDIR}` or similar and call that the `packages` target.

**Comment by Smjert** [comment]
Thanks for looking into this!

## Generating a release package and debug packages:
Release packages look fine for now and any manual change needed can be added to the CMake/CPack script.
If any of those sound like something that should exist in the generator, we can open an issue or submit a fix upstream.

Now specifically about debug packages:
There's an issue and a fix upstream, we can do a workaround for now and update the required CMake version whenever the fix is in a stable release.
There's no issue in updating the CMake version required, because it's easy to obtain and actually, this should be a no-brainer when it includes fixes the project needs.

For the binary stripping and debug symbols, the logic is correct, it could maybe have a check to warn you about the wrong interaction between `CPACK_STRIP_FILES` and `CPACK_DEBIAN_<component>_DEBUGINFO_PACKAGE`, but if you keep `CPACK_STRIP_FILES` to `OFF` and enable debuginfo packages, the debug symbols will not be left in the binaries; so this works.

For the `License`, I believe you're mentioning https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/?
If it's a matter of adding a new file into the resulting control.tar.xz, we can do that already with `CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA`, which is already used to add `conffiles` and `postinst`.
Though looking at some official Debian packages I don't see this used.
I do see though that they install a copyright and changelog files. Those can be easily added through the `install()` directive.

## Enable users to create/customize their own packages
The packaging.cmake file can be easily modified to add new files, like:
```
install(FILES "C:\Users\someone\Documents\osquery_config.conf" DESTINATION "/example/of/absolute_path")
install(DIRECTORY "C:\Users\someone\Documents\my_augeas_lenses" DESTINATION "this/is/relative/to/INSTALL_PREFIX")
```

Those directives can also appear in any place of a CMake script, guarded by checks that decide if they have to be included or not, based on CMake parameters or env vars.
This is in general better than any other alternative because it's integrated with CMake and works by default with both prefix and DESTDIR (and any build/install pre or post task).
We've also discussed in the office hours that we will separate the CPack only code in its own script so that it's possible to use CPack binary as a standalone packaging solution.
This will also include some other refactors and cleanups to better highlight where and how to modify the packaging scripts.

## FPM
FPM brings other dependencies which might eventually be difficult to install on some platforms.
We already hard depend on Python 2 and Python 3, I would prefer reducing those kind of dependencies.
One of the choices of using CPack was also the fact that it comes with CMake and being C++ means it runs pretty much everywhere.

CPack is backed by paid developers from Kitware (they also offer community and paid support) while FPM seems to be struggling for contributors right now.
Since it misses the integration with CMake, it would lack all the information that it needs to create the package.

The API you mention could be eventually useful if we see that's really needed to support multiple packaging tools more closely (vs just providing a tgz).
But keep in mind that this is a one way communication between CMake and the packaging tool, so if any customization is needed, because there's not enough info passed, one would have to modify the CMake scripts anyway.
Also this is basically repeating the work and integration that CPack already provides.

**Comment by directionless** [comment]
It sounds like this came up in office hours 2019.10.15 (@theopolis, @groob, @alessandrogario )

Watching the recording it sounds like people were starting to favor the idea that the main cpack would build tgz files, and push to a bucket.

Then a separate tool would handle a sign, package, sign flow. This tool is separate so we can more easily create security barriers around leaking keying materials. 

Other things?

**Comment by directionless** [comment]
I spent a little bit of time staring at the cpack code. It can be seen as a glorified shell script.

We've talked about how it would be nice to have the signing code live elsewhere from the normal build code. It makes it harder to exfiltrate those secrets. But, to achieve this, we really need to keep those scripts in a different code base. 

Thinking about it, I'm having a very hard time coming up with how to do that easily and keep the packaging code in cpack. As I see it, there are a couple of easy courses:
1. CI/CD builds packages on merge to master
2. CI/CD signs & uploads

or
1. CI/CD builds binaries/zips on merge to master
2. Other CI/CD, fetches zips from (1)
3. Other CI/CD signs & uploads

Secret manage is being handwaved in all of these

**Comment by theopolis** [comment]
Yes, it's more like the second flow:
- Keep the series of `install` CMake commands in the `osquery/osquery` repo.
- `osquery/osquery` has enough logic to build the TGZ package-type (all platforms).
- A new `osquery/packaging` CMake project un-tars and re-packages using deb/rpm/msi/pkg/etc. This time with the option to sign.

Then in the CI, the combination of TGZ -> packaging can always be tested. But we can also provide keying material to the second job, assuming it uses "frozen" code, let's say heavily-scrutinized pull-requests to that repo.

**Comment by theopolis** [comment]
Heads up that #6005 is related but so far does not overlap the discussion here.

**Comment by theopolis** [comment]
We'll have to port some version of this script to the new pipeline. The goal is to automate updating the website when new stable packages are available. This means syncing a copy of the table schema and the hashes of the published packages: https://github.com/theopolis/osquery/blob/experimental-portable/tools/release/new_release.sh

**Comment by theopolis** [comment]
Here are the scripts I've been using to coordinate publishing the packages: https://gist.github.com/theopolis/1638221811ad04d1787c72a51728e2c8

**Comment by mike-myers-tob** [comment]
For what it's worth, @alessandrogario and I scripted the macOS notarization workflow, and he shows here how it can be called by CMake: https://github.com/trailofbits/sinter/blob/master/packaging/scripts/notarize.sh

Again that is related to https://github.com/osquery/osquery/issues/5894

**Comment by theopolis** [comment]
I think we can call this complete. There was a lot of hard work committed to pull this off, thanks to everyone involved.

The new packaging logic: https://github.com/osquery/osquery-packaging
And the code-sign logic is in a private repo: https://github.com/osquery/osquery-codesign. Technically there is nothing private about this repo, the only private information is stored within GitHub secrets.
