### ISSUE TITLE
OSQuery failed to preparation for build due to execute make-win64-dev-env.bat  on windows

### ISSUE THREAD

**Issue by spacelg** [osquery/osquery#5692]
We (the MSVC++ team) do a nightly build of the latest OSQuery sources as a compiler "Real World Code" test. OSQuery failed to preparation for build due to execute make-win64-dev-env.bat. It can be first reproduced on 4581ec4 reversion. This commit shows remove deprecated build tools. My question is: 

is it going to switch to another build tool or we just need to delete the tools\make-win64-dev-env.bat in the script to build the OSquery project? Could you please have a look at this issue? Thanks a lot!

Repro steps:
1.git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2.Open a VS 2017 x64 command prompt and browse to D:\OSQuery
3.cd src
4.tools\make-win64-dev-env.bat

Failures:
[executing command] tools\make-win64-dev-env.bat 
'tools\make-win64-dev-env.bat' is not recognized as an internal or external command,
operable program or batch file.
[command took 0 seconds]

**Comment by Smjert** [comment]
Hi @spacelg, please follow the [BUILD.md](https://github.com/osquery/osquery/blob/master/BUILD.md) on how to build.
Those scripts are not used and not updated since osquery experimental branch (end of 2018), so we removed them.
There are two build systems right now, Buck and CMake, both rewritten from scratch.
The commit introducing Buck 971bee444168e7841bcd499867fa4c1c66ad39a6, the commit introducing CMake back https://github.com/osquery/osquery/commit/942878854b0f13129ba4b41bbeebd3c7b6cf3455.
CMake is more up to date, so I would suggest using that.

Also, the project moved under the Linux Foundation so it has a new home on github, which is https://github.com/osquery/osquery.
https://github.com/facebook/osquery is a redirect now, but I suggest updating the URL.

**Comment by spacelg** [comment]
Hi @Smjert, Thanks for you reply. 

We've updated master branch to latest commit 59a68ad. And we build follow the BUILD.md. 
My build steps:
1. git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2. Open a VS 2017 x64 command prompt and browse to D:\OSQuery
3. cd src
4. set _CL_=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING %_CL_%
[log_build.log](https://github.com/osquery/osquery/files/3485462/log_build.log)

5. mkdir build\windows10 && pushd build\windows10
6. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\..
7. cmake --build . --target osqueryd --config Release -- /maxcpucount

But we got this error: 
CUSTOMBUILD : CMake error : failed to create symbolic link 'D:/OSQuery/src/build/windows10/ns_osquery_utils_system_time/osquery/utils/system/time.h': operation not permitted 

Could you please have a look at this issue? Thanks a lot!

Thanks,
Lin

**Comment by alessandrogario** [comment]
Hello @spacelg!

Symbolic links require a special permission on Windows. You can solve this problem by either running the build as administrator, or by assigning the `SeCreateSymbolicLinkPrivilege` permission to the user account.

The setting can be found in "Local Security Policy" under Security Settings, Local Policies, User Rights Assignment

**Comment by mike-myers-tob** [comment]
Would this issue be resolved with another note in the build instructions on ReadTheDocs?

**Comment by alessandrogario** [comment]
> Would this issue be resolved with another note in the build instructions on ReadTheDocs?

To provide some context, symbolic links are created by the CMake build system in order to:
1. Generate include namespaces (simulating Buck behavior for compatibility reasons)
2. Setup the Python codegen environment

I think it is worth mentioning in the documentation!

@spacelg were you able to solve the build issue you were experiencing?
