### ISSUE TITLE
cpack creates the deb with incorrect file owners

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5796]
In https://github.com/osquery/osquery/issues/5793 we learn that the deb was created with the files owned by the build time user. They should, instead, be owned by root.

This can be seen with `dpkg-deb --contents osquery_4.0.1_1.linux.amd64.deb | head`

I see some discussion that there was a bug prior to cmake 3.12. I don't know if that's in play.

**Comment by Smjert** [comment]
I don't think there's any bug here, @theopolis should confirm?
As far as I recall it was a mistake when fixing some metadata of the DEB packages.

If you create the package it's correctly using root:root.

Also we are forcing the use of at least CMake 3.14.6, so there shouldn't be an old bug like that.

**Comment by directionless** [comment]
What kind of metadata needs human intervention?

**Comment by Smjert** [comment]
> What kind of metadata needs human intervention?

That's a good question!
I think @theopolis should answer.
He was tracking some issues here https://github.com/osquery/osquery/issues/5769, but none really metadata related, they just are things that needs to be changed/done .

**Comment by theopolis** [comment]
I thought there was an issue with the order of metadata attributes in `control`. This turned out to not be the case. The only "nitpick" remaining issues are the inability to set some fields with CPack, license being the one we 'should' include and I was not able to figure out.

I'll close this for now since it was my error.
