### ISSUE TITLE
Ubuntu 18.04 clang 6.0 OpenSSL formula fails to link with -l:libunwind.a

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5838]
This is a nice-to-have as this should work with the osquery-toolchain as described in the building guide.

```sh
$ cat formula_logs/openssl.txt
[...]
prefix/src/openssl/crypto'
making all in engines...
prefix/src/openssl/engines'

making all in engines/ccgost...
prefix/src/openssl/engines'
making all in ssl...
prefix/src/openssl/ssl'
prefix/src/openssl/ssl'
making all in apps...
prefix/src/openssl/apps'
prefix/src/openssl/apps'
/usr/bin/ld: cannot find -l:libunwind.a
```

- Ubuntu 18.04.3
- clang version 6.0.1-svn334776-1~exp1~20180919141756.113 (branches/release_60)

**Comment by Smjert** [comment]
I'm not sure what the specific issue here?
It was a choice, at least initially, to drop support for the system compiler.
We need to extract the compile/link flags that depend on the compiler used from the other osquery compiler flags, so that's possible to switch between system and custom toolchain compiler if needed.

**Comment by theopolis** [comment]
> I'm not sure what the specific issue here?
> It was a choice, at least initially, to drop support for the system compiler.

That's why I said it's a nice-to-have. :) I'm documenting this here for future reference, someone might want to explore a solution down the road.

**Comment by Smjert** [comment]
I see :)
It's just that I though that there was a specific issue with OpenSSL, while the issue I think it's more generically related to custom vs system compiler.
You would encounter this issue also with osquery itself, because we aren't explicitly specifying to use `-stdlib=libc++` for instance, so it's not only OpenSSL related.
