### ISSUE TITLE
Restore ExtensionsTest.test_extension_start test

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#5858]
# Task
The test is currently disabled and called `DISABLED_test_extension_start`.
https://github.com/osquery/osquery/blob/f2007c7057ae6d071dc448f45b7359fcde50a3b0/osquery/extensions/tests/extensions.cpp#L153

The test fails with an `SQLITE_ERROR` when calling `startExtension`.
I took a very brief stab at it and tried to track where the error originates, but I couldn't find it specifically.

**Comment by scoders-tob** [comment]
Investigation reveals that the SQLITE_ERROR originates from two cases:
1. Error because of using "WITHOUT ROWID" in sql query (#5714) ; happens in multiple tables
```
	CREATE VIRTUAL TABLE temp.user_groups USING user_groups(`uid` BIGINT, `gid` BIGINT, PRIMARY KEY (`uid`, `gid`)) WITHOUT ROWID
	SQLITE_ERROR
	near "WITHOUT": syntax error
```
2. Error because `attachTableInternal()` gets called twice
```
	CREATE VIRTUAL TABLE temp.acpi_tables USING acpi_tables(`name` TEXT, `size` INTEGER, `md5` TEXT)
	SQLITE_ERROR
	table acpi_tables already exists
```
Trace for case 2:
```

~/osquery/osquery/extensions/extensions.cpp:startExtension()
    ~/osquery/osquery/extensions/interface.cpp:registerExtension()
        ~/osquery/osquery/registry/registry_factory.cpp:addBroadcast()
            ~/osquery/osquery/registry/registry_interface.cpp:addExternal()
                ~/osquery/osquery/core/tables.cpp TablePlugin::addExternal()
                    ~/osquery/osquery/registry/registry_factory.cpp RegistryFactory::call()
                        ~/osquery/osquery/registry/registry_factory.cpp  RegistryInterface::call()
                             ~/osquery/osquery/sql/sql.cpp:  SQLPlugin::call()
                                 ~/osquery/osquery/sql/sqlite_util.cpp: SQLiteSQLPlugin::attach()
                                    ~/osquery/osquery/sql/sqlite_util.cpp: SQLiteDBManager::getConnection()
                                        ~/osquery/osquery/sql/virtual_table.cpp attachVirtualTables()
                                            ~/osquery/osquery/sql/virtual_table.cpp attachTableInternal() <--------- call 1
                                    ~/osquery/osquery/sql/virtual_table.cpp attachTableInternal()       <--------- call 2
```

Specifically,
` ~/osquery/osquery/sql/sqlite_util.cpp: SQLiteSQLPlugin::attach()`
calls both:
`~/osquery/osquery/sql/sqlite_util.cpp: SQLiteDBManager::getConnection()`
and
`~/osquery/osquery/sql/virtual_table.cpp attachTableInternal() `

Where
`~/osquery/osquery/sql/sqlite_util.cpp: SQLiteDBManager::getConnection()`
internally calls
`~/osquery/osquery/sql/virtual_table.cpp attachTableInternal()`

**Comment by scoders-tob** [comment]
In `~/osquery/osquery/sql/virtual_table attachTableInternal()`  [sqlite3_create_module()](https://github.com/osquery/osquery/blob/master/osquery/sql/virtual_table.cpp#L1079)  actually return an `SQLITE_MISUSE` value (because it has already been called for that table before), but it is being ignored and a virtual table is still being created again for one which already exists, leading to a `table already exists` error.

**Comment by scoders-tob** [comment]
Troubleshooting updates:

When I enable test_extensions_start(), I notice that all of the osquery tables belonging to the 'table' registry (starting from acpi_tables to yara_sources) get registered via REGISTER in amalgamated_native_tables.cpp.
Then when sqlite_util.cpp:getConnection() is eventually called (test_extensions_start() ->  startExtension() -> .... -> getConnection()), it calls attachVirtualTables() once when getting an sqlite instance. This attachVirtualTables() creates a virtual table for all of the registered tables above by calling attachTableInternal() on each one of them.
After this sqlite instance is created (which internally has created all vritual tables), an explicit sqlite_util.cpp:attach() is also called for all of the registered tables which again calls attachTableInternal() on each one of them, causing SQLITE_MISUSE error.

In case of osql the 'table' registry is empty i.e. REGISTER is not called for any of the tables starting from acpi_tables to yara_sources. So no such issue duplicate table creation issue arises.

So one question is whether in case of osquery (unlike osql) all these tables need to be loaded when registering an extension as is the case with test_extensions_start().

Secondly, I also brute forced getConnection() to not call attachVirtualTables() when the control flow is from sqlite_util.cpp:attach(). Then although  test_extensions_start() passes (due to no dual table creations) but if I enable  test_extensions_broadcast() as well (which is another DISABLED test)  it fails. Or vice versa.
The only way both tests pass is if I create a brand new sqlite instance inside getConnection() (which means one sqlite instance per table) instead of reusing the instance across the osquery lifetime.

**Comment by scoders-tob** [comment]
Troubleshooting updates:

When I enable test_extensions_start(), I notice that all of the osquery tables belonging to the 'table' registry (starting from acpi_tables to yara_sources) get registered via REGISTER in amalgamated_native_tables.cpp.
Then when sqlite_util.cpp:getConnection() is eventually called (test_extensions_start() -> startExtension() -> .... -> getConnection()), it calls attachVirtualTables() once when getting an sqlite instance. This attachVirtualTables() creates a virtual table for all of the registered tables above by calling attachTableInternal() on each one of them.
After this sqlite instance is created (which internally has created all vritual tables), an explicit sqlite_util.cpp:attach() is also called for all of the registered tables which again calls attachTableInternal() on each one of them, causing SQLITE_MISUSE error.

In case of osql the 'table' registry is empty i.e. REGISTER is not called for any of the tables starting from acpi_tables to yara_sources. So no such issue duplicate table creation issue arises.

So one question is whether in case of osquery (unlike osql) all these tables need to be loaded when registering an extension as is the case with test_extensions_start().

**Comment by scoders-tob** [comment]
Secondly, I also brute forced getConnection() to not call attachVirtualTables() when the control flow is from sqlite_util.cpp:attach(). Then although  test_extensions_start() passes (due to no dual table creations) but if I enable  test_extensions_broadcast() as well (which is another DISABLED test)  it fails. Or vice versa.
The only way both tests pass is if I create a brand new sqlite instance inside getConnection() (which means one sqlite instance per table) instead of reusing the instance across the osquery lifetime.

**Comment by scoders-tob** [comment]
Turns out the extension was being incorrectly linked with core tables.
