### ISSUE TITLE
Git error when clone OSQuery submodule source code on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [osquery/osquery#5958]
Hi All,

We try to build OSQuery on MSVC, we encounter the following error when we git clone the source code, can you help look at this? Thank you.

**Repro step:**

1. open VS x64 tools command
2. git clone --recursive https://github.com/facebook/osquery F:\gitP\facebook\osquery
3. cd F:\gitP\facebook\osquery
4. git submodule sync
5. git submodule foreach git reset --hard

**Error:**
**>git clone --recursive https://github.com/facebook/osquery F:\gitP\facebook\osquery**
Submodule path 'libraries/cmake/source/libgpg-error/src': checked out 'c1668f61c58ea6f0439e5193d83b4e2ac622b286'
Submodule path 'libraries/cmake/source/libiptables/src': checked out '1447b15100fe73810237809c1d4ade3c861b6d96'
Submodule path 'libraries/cmake/source/libmagic/src': checked out 'd474e35513940dbca039b510b4de705b44f5bd9c'
Submodule path 'libraries/cmake/source/librdkafka/src': checked out '8681f884020e880a4c6cda3cfc672f0669e1f38e'
Submodule path 'libraries/cmake/source/librpm/src': checked out 'bfee1410af51c1cc9724791fb8d985260a62102b'
error: unable to create file test/sys/bus/pci/devices/0000:00:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:01.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1b.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1c.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1c.1: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1c.2: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1c.3: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1d.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1d.1: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1d.2: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1d.3: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1e.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1f.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1f.1: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1f.2: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:00:1f.3: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:01:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:02:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:03:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/devices/0000:15:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/HDA Intel/0000:00:1b.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/ahci/0000:00:1f.2: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/ata_piix/0000:00:1f.1: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/e1000e/0000:02:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/iwl3945/0000:03:00.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/pcieport-driver/0000:00:01.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/pcieport-driver/0000:00:1c.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/pcieport-driver/0000:00:1c.1: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/pcieport-driver/0000:00:1c.2: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/pcieport-driver/0000:00:1c.3: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/uhci_hcd/0000:00:1d.0: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/uhci_hcd/0000:00:1d.1: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/uhci_hcd/0000:00:1d.2: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/uhci_hcd/0000:00:1d.3: Invalid argument
error: unable to create file test/sys/bus/pci/drivers/yenta_cardbus/0000:15:00.0: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:01.0:pcie00: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:01.0:pcie03: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.0:pcie00: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.0:pcie02: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.0:pcie03: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.1:pcie00: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.1:pcie02: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.1:pcie03: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.2:pcie00: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.2:pcie02: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.2:pcie03: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.3:pcie00: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.3:pcie02: Invalid argument
error: unable to create file test/sys/bus/pci_express/devices/0000:00:1c.3:pcie03: Invalid argument
error: unable to create file test/sys/bus/scsi/devices/0:0:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/devices/4:0:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/devices/7:0:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/devices/target0:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/devices/target4:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/devices/target7:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/drivers/sd/0:0:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/drivers/sd/7:0:0:0: Invalid argument
error: unable to create file test/sys/bus/scsi/drivers/sr/4:0:0:0: Invalid argument
error: unable to create file test/sys/class/bsg/0:0:0:0: Invalid argument
error: unable to create file test/sys/class/bsg/4:0:0:0: Invalid argument
error: unable to create file test/sys/class/bsg/7:0:0:0: Invalid argument
error: unable to create file test/sys/class/leds/tpacpi::bay_active: Invalid argument
error: unable to create file test/sys/class/leds/tpacpi::dock_active: Invalid argument
error: unable to create file test/sys/class/leds/tpacpi::dock_batt: Invalid argument
error: unable to create file test/sys/class/leds/tpacpi::power: Invalid argument
error: unable to create file test/sys/class/leds/tpacpi::standby: Invalid argument

**>git submodule foreach git reset --hard**
Entering 'libraries/cmake/source/libarchive/src'
HEAD is now at 98a69539 Libarchive 3.3.2
Entering 'libraries/cmake/source/libaudit/src'
HEAD is now at 20204cc Start 2.4.3 development
Entering 'libraries/cmake/source/libcryptsetup/src'
HEAD is now at 0ba5776 Version 1.7.5.
Entering 'libraries/cmake/source/libdevmapper/src'
error: unable to create file test/lib/aux.sh: No such file or directory
fatal: Could not reset index file to revision 'HEAD'.
Stopping at 'libraries/cmake/source/libdevmapper/src'; script returned non-zero status.

**Comment by Smjert** [comment]
Hi @QuellaZhang!
It's not suggested to manually clone all the submodules because they're not all needed by every platform, moreover as you can see some of those contain file names that are not supported by Windows.

When configuring with CMake, CMake itself will take care of downloading the correct submodules.
In general  please follow the build guide at https://osquery.readthedocs.io/en/latest/development/building/

**Comment by alessandrogario** [comment]
As @Smjert said, it's better to leave the submodules to CMake, but if you really need to clone the modules manually, the following list will be useful:

https://github.com/osquery/osquery/blob/0c06658e45b493583d55ec2486456e3ce44dfa35/CMakeLists.txt#L88-L128

**Comment by QuellaZhang** [comment]
@Smjert @alessandrogario Thanks for your information. Submodules are not very required. I followed the instruction at https://osquery.readthedocs.io/en/latest/development/building/ , but I got the following cmake error, cmake failed to download submodule "aws-c-common_src".

**Build steps:**

1. open VS x64 tools command
2. git clone https://github.com/osquery/osquery
3. cd osquery
4. mkdir build
5. cd build
6. cmake -A x64 -T v141 ..

**Full Log:** [log_cmake.log](https://github.com/osquery/osquery/files/3781987/log_cmake.log)

**Error:**
Submodule 'libraries/cmake/source/aws-sdk-cpp/aws-c-common_src' (https://github.com/awslabs/aws-c-common) registered for path 'libraries/cmake/source/aws-sdk-cpp/libraries/cmake/source/aws-sdk-cpp/aws-c-common_src'
Cloning into 'D:/OSQuery/osquery/libraries/cmake/source/aws-sdk-cpp/aws-c-common_src'...
error: no such remote ref 35ee33f586dfd9927f176038b2395dacf876a06f
Fetched in submodule path 'aws-c-common_src', but it did not contain 35ee33f586dfd9927f176038b2395dacf876a06f. Direct fetching of that commit failed.
CMake Error at libraries/cmake/source/modules/utils.cmake:52 (message):
  Failed to update the following git submodule:
  "D:/OSQuery/osquery/libraries/cmake/source/aws-sdk-cpp/aws-c-common_src"
Call Stack (most recent call first):
  libraries/cmake/source/modules/utils.cmake:134 (initializeGitSubmodule)
  libraries/cmake/source/modules/Findaws-sdk-cpp.cmake:10 (importSourceSubmodule)
  libraries/cmake/source_migration/modules/Findaws-sdk-cpp.cmake:7 (include)
  CMakeLists.txt:148 (find_package)
  CMakeLists.txt:68 (importLibraries)
  CMakeLists.txt:188 (main)
-- Configuring incomplete, errors occurred!
See also "D:/OSQuery/osquery/build/CMakeFiles/CMakeOutput.log".

**Comment by alessandrogario** [comment]
Hello @QuellaZhang!

Can you reset the repository with the following commands and try again?

```
git submodule deinit --force --all
git submodule sync --recursive
git reset --hard
git clean -ffdx
```

**Comment by QuellaZhang** [comment]
@alessandrogario Thanks. I tried, still got the same cmake error. [OSQuery.log](https://github.com/osquery/osquery/files/3787138/OSQuery.log)

**Comment by alessandrogario** [comment]
It seems like that machine is experiencing a bug in git we also encountered and that @theopolis looked into.

Can you remove the shallow clone setting and try again?

To disable it,  replace `SHALLOW_SUBMODULES` with `SUBMODULES` in the following file: https://github.com/osquery/osquery/blob/master/libraries/cmake/source/modules/Findaws-sdk-cpp.cmake#L13

**Comment by QuellaZhang** [comment]
Thank you very much @alessandrogario, it works. Now I can download the source code correctly. But OSQuery hit assertion when building and I am still investigating. I will update the status if I get result.
build log: [log_build.log](https://github.com/osquery/osquery/files/3793224/log_build.log)

**Comment by directionless** [comment]
That earlier version does look like what we fixed in #5897

What git version are you using?

**Comment by QuellaZhang** [comment]
D:\OSQuery>git --version
git version 2.9.2.windows.1

**Comment by theopolis** [comment]
I'm curious how much RAM the system has, we've seen that 4GB is not enough to compile the AWS dependency.

**Comment by Smjert** [comment]
> D:\OSQuery>git --version
> git version 2.9.2.windows.1

Hi @QuellaZhang, glad you were able to successfully download the source code.
I would like to mention though that the git version you're using is older than the one we normally require, which is 2.14 and higher.
This is mentioned at the top of the `Building with CMake` section.

Were you able to build or did you find any show stopper that could be related to osquery?

**Comment by QuellaZhang** [comment]
Good news. OSQuery now can be built successfully on MSVC. I updated Git to the latest version. And using "cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 .." as cmake command, because we are using a higher VCToolset version v142, it's incompatible with v141 and hit link error. 

Aha, there is a big RAM(64GB) on our test machines. Thank you very much for helping me resolve the problems. Please feel free to close this issue.

**Comment by directionless** [comment]
I'm glad it's working!

**Comment by AE1020** [comment]
I got the same error about `test\lib\aux.sh`. But this was when *building OSQuery for Linux in VirtualBox on a Windows host* when trying to clone [https://github.com/lvmteam/lvm2](https://github.com/lvmteam/lvm2). It is a NTFS filesystem.

git or VirtualBox are not the problem, since I also can't unzip the .ZIP of `lvm2-master` downloaded from GitHub in the Windows host. It gives a different error message but about the same file.

> It's not suggested to manually clone all the submodules because they're not all needed by every platform, moreover as you can see some of those contain file names that are not supported by Windows.

@Smjert it is strange because `C:\osquery\lvm2-master\test\lib\aux.sh` is just a text file and not a long path, also no unusual characters. There are no strange chmod bits making the .sh executable or anything.

However I see other files from the OP [in `udev` that contain colons](https://github.com/mfwitten/udev/tree/master/test/sys/bus/pci/drivers/pcieport-driver).  Windows [does not like that](https://stackoverflow.com/a/10386576/9308986) so it is probably a lost cause to build for Linux if using a Windows file system underneath.

What I did to work around this was format a USB stick with extfs4, and put the osquery sources there.  For VirtualBox to see the USB stick I needed to install [VirtualBox Extension Pack](https://www.virtualbox.org/wiki/Downloads) and change the Virtual Machine settings in the "USB" to USB 2.0.

Maybe you could add a **VirtualBox Linux** section alongside the **Linux** / **macOS** / **Windows 10** sections in the [Building osquery page](https://osquery.readthedocs.io/en/stable/development/building/). It would just mention a note about how this can be a problem with this project. Might mention that a USB stick with extfs on it is an easy answer, and the VirtualBox Extension Pack may be needed to do that.

**Comment by Smjert** [comment]
@AE1020 The reason for Windows failing to accept a file named `aux` (with or without an extension) is documented here https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names.
Basically it's a reserved name and identifies a device.

7z is able to uncompress it but it changes the name to `_aux.sh`.

> Maybe you could add a **VirtualBox Linux** section alongside the **Linux** / **macOS** / **Windows 10** sections in the [Building osquery page](https://osquery.readthedocs.io/en/stable/development/building/). It would just mention a note about how this can be a problem with this project. Might mention that a USB stick with extfs on it is an easy answer, and the VirtualBox Extension Pack may be needed to do that.

We try to keep instructions and build modes we support on the wiki; this is not something it's officially supported.
I wouldn't also say that this is specific to this project; many cross-platform projects needs different sets of third party libraries to work on those platforms and not every library source code can be uncompressed on all platforms.
It's not specific to osquery, it's a more generic problem.

Also I'm not sure what was your initial intention; the source code has to be downloaded directly on the platform that osquery needs to be built for and cloning submodules recursively it's not a good idea due to paths/file names issues.
Using an external USB stick unnecessarily complicates things, why not just downloading the source code inside the Linux VM?

**Comment by AE1020** [comment]
> The reason for Windows failing to accept a file named aux (with or without an extension) is documented here

Oh.

> Using an external USB stick unnecessarily complicates things, why not just downloading the source code inside the Linux VM?

Yes, you are right.  I forget this is just my personal quirk of not wanting to put any personal project work inside VMs, because I blow them away very casually. I do not like having them contain anything I am actually working on as source code. I try to keep everything on host drives, shareable between VMs easily and backed up separately.
