### ISSUE TITLE
Try out Ninja

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#5968]
The windows builds have gotten very slow. This is because we're rebuilding the AWS EC2 sdk each time. This requires a lot of ram, and as the CI machines are small it's a fairly slow process.

One of the factors here is that the cmake builds (especially on windows) do not support partial rebuilds. We believe ninja would help with that. 

Cc: @alessandrogario @Smjert @muffins

relates to: #5967

**Comment by Smjert** [comment]
So, a correction here: partial rebuilds are supported. The issue pertaining to build systems is that msbuild is first of slow when it has to detect which project/source file really changed.
Second, it has a job scheduling systems that leave much to be desired, so instead of having all the cores used most of the time, it requires you to fiddle with the configuration and end up either not having enough jobs running concurrently, or too many.

Ninja excels in both of this; though it currently produces binaries which have some tests (virtual table tests specifically), which segfault in some boost co-routine code.

My intuition in this is that msbuild puts some default flags that Ninja doesn't which either correctly fix or simply hide the issue in the builds.
But I would also like to add that on Windows, some of the pre-built libraries have mixed CRT which might cause issues in one way or the other, so another step here is to move to source based builds.

**Comment by Smjert** [comment]
To try Ninja:
1) Download the latest version from https://github.com/ninja-build/ninja/releases
2) Extract it where you want and then add that path to your User or System PATH environment variable
3) Open a cmd console and run the following command to initialize the needed Visual Studio env vars
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.1
```
4) Configure using cmake, with the usual arguments but also `-G Ninja`
5) Build using the `ninja` command or using `cmake --build . --config <CMAKE_BUILD_TYPE>`

By default Ninja runs with an amount of jobs that is equal to the number of the cores (HT included) + 2.
You can control the number of jobs as usual with the `-j` parameters with both commands.

**Comment by Smjert** [comment]
The issues described here have been fixed.
