### ISSUE TITLE
Testing Browser Tables Blueprint

### ISSUE THREAD

**Issue by rcipkins** [osquery/osquery#6069]
In order to run unit tests on browser related tables (eg. chrome_extensions, firefox_addons) an instance of that browser must be present on the machine. 

Therefore an instance of the browser would have to be placed on the CI in order for testing to work properly. 

Is there an alternative way to support this?

**Comment by directionless** [comment]
That's a good question. 

I'm not sure how it would fit in this testing infra, but one way I've done this in the past is to ship the data files that it would be reading.

**Comment by mike-myers-tob** [comment]
Using some static files pulled from a real Chrome profile seems like a good compromise, and would involve the least additional overhead on our CI builds.

We will just have to occasionally update these files in order to ensure that the tests are testing a semi-current version of Chrome profile file format.
