### ISSUE TITLE
Unicode Characters mis-encoded in Users and Logged_In_Users tables

### ISSUE THREAD

**Issue by FritzX6** [osquery/osquery#6160]
# Bug report

### What operating system and version are you using?

Windows 10 Pro
### What version of osquery are you using?

4.1.1
### What steps did you take to reproduce the issue?
Querying the `users:directory` and `logged_in_users:user` columns in osquery does not properly encode some characters.

Specifically this is being observed with the following character: `ø`

### I am not a developer but I suspect...

Eyeballing some other issues, this behavior appears to have been fixed in other columns on other tables. https://github.com/osquery/osquery/pull/4705

The users:username column has the following line:
https://github.com/osquery/osquery/blob/c18f5bc75c84ec1891309b5dee07a0d459997a83/osquery/tables/system/windows/users.cpp#L111
`wstringToString`

---

This conversion does not appear to be applied to the following columns so far as I can tell:
`users:directory`
https://github.com/osquery/osquery/blob/c18f5bc75c84ec1891309b5dee07a0d459997a83/osquery/tables/system/windows/users.cpp#L83

`logged_in_users:user`
https://github.com/osquery/osquery/blob/c18f5bc75c84ec1891309b5dee07a0d459997a83/osquery/tables/system/windows/logged_in_users.cpp#L71

### What did you expect to see?
This is creating a problem wherein I am trying to `JOIN` the `users` and `logged_in_users` table the following way:

```SQL
SELECT 
  DISTINCT(uid), 
  u.username, 
  liu.user 
FROM users u, logged_in_users liu 
WHERE u.username = liu.user;
+-----+------------+------------+
| uid | username   | user       |
+-----+------------+------------+
| 502 | frøtz-jorn | frøtz-jorn |
+-----+------------+------------+
```

### What did you see instead?

Instead I am getting no results returned. This is because the `users:username` column supports the UTF-8 encoding required to display the unicode `ø` character but the `logged_in_users:user` column does not.

If I try to run each query in isolation I see the following:
```SQL
osquery> SELECT uid, username, directory FROM users where uid = 502;
+-----+------------+---------------------+
| uid | username   | directory           |
+-----+------------+---------------------+
| 502 | frøtz-jorn | C:\Users\fr�tz-jorn |
+-----+------------+---------------------+
```

```SQL
osquery> select * from logged_in_users where tty = 'console';
+------+------------+---------+------+------------+-----+
| type | user       | tty     | host | time       | pid |
+------+------------+---------+------+------------+-----+
| user | fr�tz-jorn | console |      | 1576247241 | 226 |
+------+------------+---------+------+------------+-----+
```

**Comment by muffins** [comment]
Yeah this is a relatively known issue. The encoding support throughout Windows has always been relatively shitty.

**Comment by farfella** [comment]
Would it be an acceptable approach to rewrite conversions\windows\strings.cpp to use native Windows API functions instead of using `std::codecvt_utf8_utf16` (this appears to be the buggy culprit)? I noticed `getUserHomeDir` working, which is ultimately calling `advapi32!RegQueryValueExA`, which is then calling `KernelBase!RtlUnicodeToMultiByteN`, and performing the conversion appropriately. Based on this information, I tried CP_ACP, and this correctly converts UTF-8 <-> UTF-16 conversion. So, the functions provided by Windows API appear to be converting back-and-forth just fine.

This is the correct output I am able to produce:

```
osquery> SELECT uid, username, directory FROM users where uid = 1003;
+------+------------+---------------------+
| uid  | username   | directory           |
+------+------------+---------------------+
| 1003 | fr°tz-jorn | C:\Users\fr°tz-jorn |
+------+------------+---------------------+
osquery> SELECT
    ...>   DISTINCT(uid),
    ...>   u.username,
    ...>   liu.user
    ...> FROM users u, logged_in_users liu
    ...> WHERE u.username = liu.user;
+------+------------+------------+
| uid  | username   | user       |
+------+------------+------------+
| 1001 | user       | user       |
| 1003 | fr°tz-jorn | fr°tz-jorn |
+------+------------+------------+
osquery> SELECT uid, username, directory FROM users
    ...> ;
+------+--------------------+---------------------------------------------+
| uid  | username           | directory                                   |
+------+--------------------+---------------------------------------------+
| 500  | Administrator      |                                             |
| 1003 | fr°tz-jorn         | C:\Users\fr°tz-jorn                         |
| 18   | SYSTEM             | %systemroot%\system32\config\systemprofile  |
| 19   | LOCAL SERVICE      | %systemroot%\ServiceProfiles\LocalService   |
| 20   | NETWORK SERVICE    | %systemroot%\ServiceProfiles\NetworkService |
+------+--------------------+---------------------------------------------+
osquery>  select type, user, tty, host, time, pid from logged_in_users;
+--------------+------------+----------+------+------------+-----+
| type         | user       | tty      | host | time       | pid |
+--------------+------------+----------+------+------------+-----+
| disconnected |            | Services |      | 0          | -1  |
| down         |            |          |      | 1579063587 | -1  |
| active       | user       | Console  |      | 1579224397 | -1  |
| disconnected | fr°tz-jorn |          |      | 1579224352 | -1  |
+--------------+------------+----------+------+------------+-----+
```

**Comment by farfella** [comment]
Now, I know what you're thinking: Why is it `fr°tz-jorn` instead of `frøtz-jorn`? Well, that's a separate bug and related to printing to console. :-)

**Comment by farfella** [comment]
Upon, further research std::codecvt_utf8_utf16 is actually deprecated in C++17 (https://en.cppreference.com/w/cpp/locale/codecvt_utf8_utf16). So, CP_ACP is the approach to use.

**Comment by muffins** [comment]
@farfella that sounds great! Let us know if you need any help or anything, I'm happy to do reviews and that sounds like a great approach, thanks!

**Comment by farfella** [comment]
Sure thing! Happy to help. :-) I'm new to the project, so feedback is appreciated, and apologies while I get up-to-speed with code-style and the overall processes for the project.

**Comment by farfella** [comment]
Upon further inspection, the `getUserHomeDir` -> `RegQueryValueExA` -> `RtlUnicodeToMultiByteN`  case was working because it was converting from UTF-16 to the system default code page (CP_ACP), which the console is set to by default. That is, `RtlUnicodeToMultiByteN` narrows/widens based on the regional settings the computer is using (CP_ACP). However, CP_ACP produces in different behavior on different regional settings, and conversion should in fact be performed to CP_UTF8, in the case of this project. In previous comments, I thought Windows 10 was using UTF-8 as CP_ACP now, based on that one comment in WinNls.h... but that is not the case.

So, the PR for this issue updates the console's input and output to use CP_UTF8 instead of CP_ACP. The strings code is updated to use CP_UTF8, as well. I only fixed the first call in `logged_in_users.cpp` to use the wide version (`WTSQuerySessionInformationW`) and then narrow this to UTF-8. But it looks like there are many places that use the narrow (`*A`) flavors of these functions, and these will produce regional equivalents of the strings (as per above paragraph) vs UTF-8. We ought to update these cases gradually vs in this PR. Maybe for future PRs, we can shy folks away from using the *A versions of these functions and encourage them to use the *W versions instead.
