### ISSUE TITLE
curl -> Error making request: certificate verify failed

### ISSUE THREAD

**Issue by arimboor** [osquery/osquery#6269]
getting the "certificate verify failed" error while trying `select url, round_trip_time, response_code from curl where url = 'https://github.com/facebook/osquery';`

**Comment by Smjert** [comment]
Hi @arimboor!
Can you give us some more information about your platform and how you got a hold of osquery?
Is it compiled? Installed?

I just tried and the table works fine here, most likely it's because you don't have the standard CA certificates installed on the system (or somehow osquery doesn't find them).

**Comment by arimboor** [comment]
Is it compiled? Installed? - > installed, 
which version of osquery are you using? - > 4.2.0
platform - > ubuntu server 18.x

**Comment by muffins** [comment]
Just as a data point, I grabbed the osquery 4.2.0 macos package hosted on the site and ran the query:

```
❯ osqueryi
Using a virtual database. Need help, type '.help'
osquery> select url, round_trip_time, response_code from curl where url = 'https://github.com/facebook/osquery';
+-------------------------------------+-----------------+---------------+
| url                                 | round_trip_time | response_code |
+-------------------------------------+-----------------+---------------+
| https://github.com/facebook/osquery | 3126108         | 200           |
+-------------------------------------+-----------------+---------------+
```

All looks to be well. @arimboor can you share any `osquery.flag` files you might have on your system? We just made some changes to how osquery does SNI hostname validation, I'd like to try and rule out any regressions that may have occured..

**Comment by arimb00r** [comment]
here is .flags file

--enroll_secret_path=/var/osquery/enroll_secret
--tls_server_certs=/var/osquery/server.pem
--tls_hostname=nix_uc_kolide:8080
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=filesystem
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=3
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write

here is the .conf file

{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "tls,filesystem",
    "logger_path": "/var/log/osquery/",
    "utc":"true"
  },

**Comment by theopolis** [comment]
This is an issue because osquery applies the certificate bundle from `--tls_server_certs` to all TLS requests, including the `curl` and `curl_certificate` table. A fix includes adding the default bundle to the set of certs in `/var/osquery/server.pem`. The default bundle can be found from `select * from osquery_flags` (look at `default_value` for `tls_server_certs`).
