### ISSUE TITLE
4.2.0 macOS PKG does not register service

### ISSUE THREAD

**Issue by jalseth** [osquery/osquery#6282]
# Bug report

The macOS PKG installer does not register the service with launchd. 

### What operating system and version are you using?

macOS 10.15.3

### What version of osquery are you using?

4.2.0

### What steps did you take to reproduce the issue?

```
curl -O https://pkg.osquery.io/darwin/osquery-4.2.0.pkg
sudo installer -pkg osquery-4.2.0.pkg -target /
launchctl list | grep osquery
ps aux | grep osqueryd
```

### What did you expect to see?

`com.facebook.osqueryd` listed and `osqueryd` running.

### What did you see instead?

No results.

**Comment by keeleysam** [comment]
This is expected behavior - the official packages have never installed a service.

https://osquery.readthedocs.io/en/latest/installation/install-macos/#running-osquery

There's also the osqueryctl helper which can install the service for you https://osquery.readthedocs.io/en/stable/deployment/configuration/#osqueryctl-helper

I do not think that the package should install or manage the service on macOS, it should remain an optional component.

**Comment by jalseth** [comment]
Hmm... OK. Why does it do so on Windows then? The behavior should be consistent across all platforms.

**Comment by mike-myers-tob** [comment]
The [homebrew cask has an uninstall step](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osquery.rb) for the service, but maybe not because it was intending to install it but because the user might have installed it.

It looks like osqueryctl is available for macOS and Linux (not Windows?), and that may be why the installer is doing the service registering for Windows.

Does @theopolis know?

**Comment by theopolis** [comment]
IIRC we wanted to avoid osquery starting on install. On macOS instead of installing the LaunchDaemon plist and running a script to disable it, we choose to require `osqueryctl`.

At this point I would defer to the macOS sysadmins here for guidance on what the correct behavior / expectation should be.
