### ISSUE TITLE
Remove Buck? (March 2020 edition)

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#6305]
# Question

https://github.com/osquery/osquery/pull/6302 updates openssl for cmake. But **not** for buck. Having a diverged openssl library is fine technically, but creates a place for CVEs to slip in.

Thus, it's time to re-open the question. Should we keep buck support?

My personal take, is that I entirely want to defer to @theopolis and @muffins here.

**Comment by theopolis** [comment]
It has been pretty easy to merge changes back and forth manually. I don't think the Buck support on GitHub is a big factor in keeping the FB and GitHub changes from being synced. I say this with the caveat that it is a manual process.

Slightly different topic, we can use the logic in CMake to bootstrap Buck's third-party libraries. This sounds OK since it is sticking to CMake's intended usage, to bootstrap other build systems. The majority of changes would be changing Buck logic to expect files/headers for these targets to always exist in a relative `./build` directory.

Buck or no-Buck, I'll continue to merge changes for the foreseeable future. :)

**Comment by muffins** [comment]
I don't have much preference anymore. Lately I've largely been making due with the CMake build, so haven't been leveraging the Buck build system at all really. I don't have any preference, and honestly at this point I think it might be better to drop it if there's no good reasons to keep it around as it's added overhead on master.

**Comment by directionless** [comment]
#6361 merged. I'm closing this.
