### ISSUE TITLE
Default Windows filesystem permissions on 'C:\Program Files' to unsafe for osquery?

### ISSUE THREAD

**Issue by robschi** [osquery/osquery#6313]
```
version = 10.0.14393
   build = 14393
platform = windows
```
`version = 4.2.0`

For some reason osquery does set the following explicit filesystem permissions on  "C:\Program Files\osquery\osqueryd"
```
Get-Acl "$env:ProgramFiles\osquery\osqueryd" | Format-List

Path   : Microsoft.PowerShell.Core\FileSystem::C:\Program Files\osquery\osqueryd\
Owner  : BUILTIN\Administrators
Group  : NT AUTHORITY\SYSTEM
Access : NT AUTHORITY\SYSTEM Allow  FullControl
         BUILTIN\Administrators Allow  FullControl
         BUILTIN\Users Allow  ReadAndExecute, Synchronize
Audit  :
Sddl   : O:BAG:SYD:P(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)(A;OICI;0x1200a9;;;BU)

```
When you clear this permissions and enable the inheritance from parent, because the permissions on "C:\Program Files" are already safe, the service osqueryd can no longer start and claims that the new permissions are to unsafe to run osqueryd
```
"C:\Program Files\osquery\osqueryd\osqueryd.exe" --flagfile="C:\Program Files\osquery\osquery.flags" --verbose
I0316 16:09:17.159752  3052 init.cpp:340] osquery initialized [version=4.2.0]
I0316 16:09:17.178764  3052 system.cpp:330] Found stale process for osqueryd (1108)
I0316 16:09:17.179766  3052 system.cpp:362] Writing osqueryd pid (2352) to \Program Files\osquery\osqueryd.pidfile
I0316 16:09:17.183768  3052 extensions.cpp:349] Could not autoload extensions: Failed reading: \Program Files\osquery\extensions.load
E0316 16:09:17.190773  5632 watcher.cpp:567] [Ref #1382] osqueryd has unsafe permissions: C:\Program Files\osquery\osqueryd\osqueryd.exe

```

**Comment by muffins** [comment]
Hey @robschi, sorry you're hitting issues with the renowned "safe file" perms!

We have some pretty complicated logic that checks for `osqueryd.exe` and it's parent folder to ensure that osquery isn't susceptible to getting hot-swapped out on launch. We've documented the manual process one can take to ensure that the [file permissions are safe on our read the docs](https://osquery.readthedocs.io/en/latest/installation/install-windows/), but on install we set them explicitly to ensure that a user hopefully doesn't need to handle these permissions.

>  the permissions on "C:\Program Files" are already safe

You're correct here, in theory, these permissions _should_ be sufficiently safe for `osqueryd` to run, however what's likely happening is the ordering of the ACL might be not quite what osquery is expecting or you may have other GUIDs listed on the ACL that osquery is likely not gunna accept, see my sample below. My system _might_ not be the best example, but it's relatively "clean", and as you can see `Program Files` brings a long quite a few permissions that we explicitly want to prevent from applying to `osqueryd.exe` just to ensure safety as we can't make guarantees on all of these GUIDs:
```
PS C:\Users\Nicholas\work\repos\osquery> Get-Acl "$env:ProgramFiles" | Format-List


Path   : Microsoft.PowerShell.Core\FileSystem::C:\Program Files
Owner  : NT SERVICE\TrustedInstaller
Group  : NT SERVICE\TrustedInstaller
Access : CREATOR OWNER Allow  268435456
         NT AUTHORITY\SYSTEM Allow  268435456
         NT AUTHORITY\SYSTEM Allow  Modify, Synchronize
         BUILTIN\Administrators Allow  268435456
         BUILTIN\Administrators Allow  Modify, Synchronize
         BUILTIN\Users Allow  -1610612736
         BUILTIN\Users Allow  ReadAndExecute, Synchronize
         NT SERVICE\TrustedInstaller Allow  268435456
         NT SERVICE\TrustedInstaller Allow  FullControl
         APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES Allow  ReadAndExecute, Synchronize
         APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES Allow  -1610612736
         APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES Allow  ReadAndExecute, Synchronize
         APPLICATION PACKAGE AUTHORITY\ALL RESTRICTED APPLICATION PACKAGES Allow  -1610612736
Audit  :
Sddl   : O:S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464G:S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464D:PAI(A;OICIIO;GA;;;CO)(A;OICIIO;GA;;;SY)(A;;0x1301bf;;;SY)(A;OICIIO
         ;GA;;;BA)(A;;0x1301bf;;;BA)(A;OICIIO;GXGR;;;BU)(A;;0x1200a9;;;BU)(A;CIIO;GA;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;;FA;;;S-1-5-80-956008885-3418522649-1831038044-18532
         92631-2271478464)(A;;0x1200a9;;;AC)(A;OICIIO;GXGR;;;AC)(A;;0x1200a9;;;S-1-15-2-2)(A;OICIIO;GXGR;;;S-1-15-2-2)
```
We re-wrote this logic some time ago to make the permissions a bit more relaxed, but ultimately we strongly recommend not clearing out the ACL to ensure osquery can run as expected. Hope that this helps clear things up, let us know if you'd like to chat further about this, and we definitely welcome Pull Requests if you'd like to take a stab at [fixing up the logic](https://github.com/osquery/osquery/blob/master/osquery/filesystem/windows/fileops.cpp#L847). Otherwise I'm going to close this out for now, feel free to re-open if you'd like!
