### ISSUE TITLE
https://osquery.io/schema/#ntfs_journal_events is dead

### ISSUE THREAD

**Issue by CaledoniaProject** [osquery/osquery#6367]
I got the following error message while configuring file events

```
W0406 17:50:22.666654  2084 virtual_table.cpp:974] Please see the table document
ation: https://osquery.io/schema/#ntfs_journal_events
```

And the link https://osquery.io/schema/#ntfs_journal_events is dead, it no longer pointer to the right document, please fix it.

**Comment by Smjert** [comment]
Hi @CaledoniaProject!
The problem here is that the correct link must contain the osquery version, so https://osquery.io/schema/4.2.0#ntfs_journal_events.

Though the link without the version in theory is correct, in practice the website is not currently able to route it (although in the past it was).
I think we have to restore that functionality on the website, the issue tracking this is: https://github.com/osquery/osquery-site/issues/51

**Comment by zwass** [comment]
![giphy](https://user-images.githubusercontent.com/575602/78705585-8cd55080-78c2-11ea-9c27-aa4d2e38dd38.gif)
