### ISSUE TITLE
Incorrect presentation of empty registry data in "startup_items" table

### ISSUE THREAD

**Issue by 1ihor1** [osquery/osquery#6403]
# Bug report

### What operating system and version are you using?

 version = 10.0.17763
   build = 17763
platform = windows
### What version of osquery are you using?

version = 4.3.0 (and older)
### What steps did you take to reproduce the issue?
osqueryi "select * from startup_items where name = 'Zoom';" 
where 'Zoom' is a Registry value with an empty value data, but it can be any other value name with an empty value data
### What did you expect to see?
"Startup_items" table with "Zoom" entry having empty "path" & "args" columns.
### What did you see instead?
path = 'c:\Program'
args = 'Files\osquery\osqueryi.exe'

![image](https://user-images.githubusercontent.com/36096154/79681113-870f3180-8217-11ea-824e-7a9d741b64a2.png)

**Comment by mike-myers-tob** [comment]
Just confirmed this in testing.

**Comment by mike-myers-tob** [comment]
The problem is over in osquery/env.cpp with the call to `CommandLineToArgvW`

https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw

If passed a NULL string, it doesn't return NULL results, it assumes you wanted to parse *your* command-line (of osquery.exe, the current process).
