### ISSUE TITLE
Severe memory and performance issues when joining users table

### ISSUE THREAD

**Issue by tferguson7337** [osquery/osquery#6411]
# Bug report

### What operating system and version are you using?

Windows Server 2016

### What version of osquery are you using?

osqueryi (shell) 3.3.2, 4.1.2, and 4.3.0

### What steps did you take to reproduce the issue?

Run the following query from a high-user count system:
- E.g., domain controller server with large number of domain users
- or any machine with large number of local users.

> SELECT * FROM users JOIN chrome_extensions USING (uid);

### What did you expect to see?

Timely results, reasonable memory usage.

### What did you see instead?

No results (pretty sure osquery crashed), took 8 days to run before crashing, extremely high memory usage (~11/16 GB used at peak, averaging ~7GB over 8 days).

The domain controller server in question services ~100K accounts.  Expectation was that the users table would include local accounts, but long run time and memory usage suggest that all accounts on the domain were being enumerated.  Regardless of enumeration behavior, the run time and memory usage was extremely debilitating to the server and the machines that rely on it.

Looking through the users table Windows code, the [NetUserEnum call that drives the enumeration](https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/users.cpp#L125) is using a filter value of 0, which may be causing the domain enumeration; I am curious if FILTER_NORMAL_ACCOUNT would make the enum more targeted to avoid over-enumeration.

Testing with osqueryi 3.3.2, 4.1.2, and 4.3.0 on local non-server VMs that have 10,000 local accounts demonstrates similar behavior.  The query has been running for several hours now, using a significant amount of memory.

> SELECT * FROM users;

does not result in unreasonably long run duration or high memory usage on these test VMs.  It seems to be only when joining the chrome_extensions and users tables.  I imagine joining users with other tables may have the same effect.

Two main points:

- It's not clear if the users table should include all domain users, notably in this case where the query is run on a domain controller server.  If it is intended, this doesn't seem like desirable behavior for large domains.
- There is a major performance and resource issue with queries that involve joining with the users table when there are a large number of users that osquery can query.

**Comment by Smjert** [comment]
NIce catch!

This can be explained by the fact that while the users table spec says that `uid` is an index, the Windows implementation of that table doesn't support that column to be an index and so it doesn't optimize the query based on it.
When a column is an index and a JOIN is done what is expected is that the table will do an optimization and only search and return that column value because for each row to JOIN sqlite will call the table row generation; instead here everytime the table generation code is called, all the users are retrieved and almost all then discarded later by sqlite, because only one uid is really needed.

As for querying users on a domain, I was aware too that doing network calls of that type should be avoided or at least maybe they should be behind a special column/differently named table.

**Comment by mike-myers-tob** [comment]
This PowerShell script creates an arbitrary number of user accounts (disabled with no password, but usable for testing).
https://gist.github.com/mike-myers-tob/1f30c1f0ba994b31d9f7c3cd40bf50ee

In the gist I've included the link to a 100,000 row CSV, to create that many new local user accounts. This actually works on Windows 10 Pro. They're not domain accounts, but according to @tferguson7337 it should still be able to replicate the severe performance issues.

First I created 10,000 users, and ran the following in PowerShell:

```PowerShell
PS C:\Projects\osquery-tob\build> .\osquery\RelWithDebInfo\osqueryi.exe "select COUNT() from users;"
+---------+
| COUNT() |
+---------+
| 10017   |
+---------+
PS C:\Projects\osquery-tob\build> Measure-Command {.\osquery\RelWithDebInfo\osqueryi.exe "select COUNT() from users;"}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 7
Milliseconds      : 84
Ticks             : 70849444
TotalDays         : 8.20016712962963E-05
TotalHours        : 0.00196804011111111
TotalMinutes      : 0.118082406666667
TotalSeconds      : 7.0849444
TotalMilliseconds : 7084.9444
```

7 seconds is a little slow but doesn't seem to reproduce the severe behavior. I tried again after creating 100,000 local user accounts.

```Powershell
PS C:\Projects\osquery-tob\build> Measure-Command {.\osquery\RelWithDebInfo\osqueryi.exe "select COUNT() from users;"}


Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 31
Milliseconds      : 876
Ticks             : 1518767233
TotalDays         : 0.00175783244560185
TotalHours        : 0.0421879786944444
TotalMinutes      : 2.53127872166667
TotalSeconds      : 151.8767233
TotalMilliseconds : 151876.7233

PS C:\Projects\osquery-tob\build> .\osquery\RelWithDebInfo\osqueryi.exe "select COUNT() from users;"
+---------+
| COUNT() |
+---------+
| 100017  |
+---------+
```

The CPU usage on a 3-core Windows 10 Pro VM never exceeded 25%, and memory overhead fluctuated around 50MB, but I wasn't seeing the severe issues that have been reported.

I am looking at optimizing the NetUserEnum API but can anyone identify the difference in these local users and the systems where the problems exist?

As @Smjert pointed out, the table needs to implement the "index" on the `UUID` column; otherwise it's true that `JOIN` operations get out of hand. I'm working on that too.
