### ISSUE TITLE
kernel version - Inaccurate information 

### ISSUE THREAD

**Issue by torgeman** [osquery/osquery#6452]
# Bug report

### What operating system and version are you using?
Windows 10 - version 1909 (OS build 18363.778)

### What version of osquery are you using?
4.3.0

### What steps did you take to reproduce the issue?
osquery: 
`select version from kernel_info`

cmd:
`winver
`
### What did you expect to see?
The same kernel version on osquery query as well 

### What did you see instead?
![image](https://user-images.githubusercontent.com/7221829/82343927-1ae14280-99fc-11ea-83f1-0b18397c60ab.png)

**Comment by mike-myers-tob** [comment]
`kernel_info` actually reads the file version info for `%WINDIR%\System32\ntoskrnl.exe` https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/kernel_info.cpp

Whereas, `winver.exe` reportedly reads [the Registry](https://stackoverflow.com/questions/33641076/retrieving-windows-version-1511/33661494#33661494) key `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ReleaseID` and this might be the way to go.

I thought maybe it should be using the `GetVersionEx` API, but Microsoft appears to want to deprecate that in order to prevent application developers from trying to use OS version checks to make decisions. So, maybe that ought to be avoided.

**Comment by farfella** [comment]
Kernel version is the version of NTOSKRNL.exe. The other info is "OS Build." So, kernel's version might be less than OS Build.

Reference 1: http://www.geoffchappell.com/studies/windows/km/ntoskrnl/history/

**Comment by Smjert** [comment]
I'm closing this, since the table is showing the correct data.
If you need the OS version, you have to query the `version` column of the `os_version`table, although it won't have the very last part, the Update Build Revision (778 in your image).
