### ISSUE TITLE
Interdependency when starting osqueryd and its plugins should be avoided

### ISSUE THREAD

**Issue by taojwmware** [osquery/osquery#6524]
# Bug report

### What operating system and version are you using?

Windows 10.

### What version of osquery are you using?

4.3.0

### What steps did you take to reproduce the issue?

It has been discussed in slack: https://osquery.slack.com/archives/C08V7KTJB/p1593012420299200

Once osqueryd started with --extensions_socket=\\\\.\\pipe\\osqery.em

The custom table can be attached to osquerd and working fine using:
python foobar_table.ext --socket \\\\.\\pipe\\osqery.em

However, After the configure or logger plugin attached using
python foobar_logger.ext --socket \\\\.\\pipe\\osqery.em
The logger is not activated and nothing is logged. As suggested by @theopolis , it can be fixed by using either autoloading or updating config file or flags to let osqueryd to configure the logger.

However, there are a few concerns on this approach:
1. When extension crashes, osqueryd has to be restarted to fix it. 
2. When custom logger component has some custom logic to process and send log to remote place, it is hard to coordinate two different processes for restarting.

### What did you expect to see?

logger and config plugin work the same ways as table plugin. They should be activated automatically once attached to osqueryd without any further tweak in configuration. 

The plugin should be able to restart at any time. 

### What did you see instead?

logger or configure plugin has to be started as autoloading or tweaking the osquery.conf to logger name and also update osquery.flags by adding --extensions_timeout=600
--extensions_require=foobar_logger to let osqueryd enough time to wait for logger to start because logger cannot start/attach to socket until osqueryd started. 

I also observed that if plugin crashes, the osqueryd crashes after that. The recover sequence to restart osqueryd first then, restart plugin. I think it's better to avoid this inter-dependency.

**Comment by taojwmware** [comment]
So far, the only workaround for this I found is to use [remote settings](https://osquery.readthedocs.io/en/stable/deployment/remote/) similar to [Doorman](https://github.com/mwielgoszewski/doorman)'s approach.

**Comment by theopolis** [comment]
Right now osquery needs to have the `config` and `logger` plugins available before it starts. I think that makes sense from a design perspective, at least for the config, since you cannot really start doing anything until you know your configuration. For logging there could be some "buffer all logs" until the logger plugin is available but I think dynamically adding/removing loggers is complex and it is easier to require all of these plugins to be known before starting.

I think your two concerns:

> However, there are a few concerns on this approach:
> 1. When extension crashes, osqueryd has to be restarted to fix it.
> 2. When custom logger component has some custom logic to process and send log to remote place, it is hard to coordinate two different processes for restarting.

Are essentially the same, correct? If osquery autoloads extensions and those extensions crash, osquery should try to restart them but osquery itself should not restart.

So let's try this:

```
./osquery/osqueryd \
  --config_path ./schedule-test.json \
  --ephemeral \
  --extension ~/git/osquery-python/examples/foobar_logger.ext \
  --logger_plugin foobar_logger \
  --extensions_socket /tmp/osquery.em 
```

This works, and I can see the following processes:

```
teddy    23490  0.2  0.0 130252 26692 pts/1    SNl+ 23:27   0:00 ./osquery/osqueryd --config_path ./schedule-test.json --ephemeral --extension /home/teddy/git/osquery-python/examples/foobar_logger.ext --logger_plugin foobar_logger --extensions_socket /tmp/osquery.em
teddy    23492 11.3  0.0 435952 30360 pts/1    SNl+ 23:27   0:09 ./osquery/osqueryd
teddy    23493  0.0  0.0  55532 15032 pts/1    SN+  23:27   0:00 python /home/teddy/git/osquery-python/examples/foobar_logger.ext --socket /tmp/osquery.em --timeout 3 --interval 3
```

If I issue a `kill 23493` to crash the logger plugin, then I see

```
Thrift: Fri Jul  3 23:32:34 2020 TSocket::open() connect() <Host:  Port: 0>Connection refused
I0703 23:32:34.082995 23495 extensions.cpp:341] Extension UUID 57496 has gone away
I0703 23:32:34.792680 23787 interface.cpp:108] Registering extension (foobar_logger, 46448, version=1.0.0, sdk=1.8.0)
```

Here osquery attempted to restart the crashed extension without restarting osquery itself. So I think "The plugin should be able to restart at any time." is reality, you can restart this extension at anytime but osquery will try to restart it again.

Are you observing something different?

**Comment by taojwmware** [comment]
Thanks for taking a look on the issue! Yes, osqueryd did restart the plugin.

In our case, We have multiple non-trivial downstream micro-services (owned by different team and more to come) consuming the data from osquery. Modeling those services as plugins make them tightly coupled and also more resource consumption for osquery to support multiple subscribers.

I was originally thinking about using filesytem logger to dump out all info and let each services to consume event from log file (a poor man's version of Kafka). But, I later feel tls plugin could be better solution.

**Comment by theopolis** [comment]
Let me know if we need to discuss any more of osquery's extension handling.
