### ISSUE TITLE
tls logger generating "cannot parse JSON: Invalid value. Offset: 0" error

### ISSUE THREAD

**Issue by rd2seu** [osquery/osquery#6525]
# Bug report

### What operating system and version are you using?

`version = 10.15.5
   build = 19F101
platform = darwin`

### What version of osquery are you using?

`version = 4.3.0`

### What steps did you take to reproduce the issue?

> Set up a local API for enrollment and logging
> Start up osquery in ephemeral mode to test:
`sudo osqueryd --verbose --ephemeral --tls_hostname localhost:8082 --config_plugin filesystem --enroll_tls_endpoint /osquery/enroll --logger_plugin tls --logger_tls_endpoint /osquery/logger --enroll_secret_path enroll_secret.txt --tls_server_certs dev.cert.pem`

### What did you expect to see?
> Expected see the enrollment negotiation (which we saw on the server side) and server return a node_key:
`{
  "node_invalid": false,
  "node_key": "node_key"
}`

> Expected to see a subsequent results or status logs sent from client to server

### What did you see instead?

> Client fails to send HTTP POST. Instead we see:

`I0626 02:07:10.108399 220360704 tls.cpp:253] TLS/HTTPS POST request to URI: https://localhost:8082/osquery/logger
I0626 02:07:10.117561 220360704 buffered.cpp:74] Error sending results to logger: Cannot parse JSON: Invalid value. Offset: 0`

> and

`I0626 02:07:02.002811 220360704 tls.cpp:253] TLS/HTTPS POST request to URI: https://localhost:8082/osquery/logger
I0626 02:07:02.010893 220360704 buffered.cpp:89] Error sending status to logger: Cannot parse JSON: Invalid value. Offset: 0`

> Note the failure on both invocation of send() (for both result and status).

**Comment by FreddieOliveira** [comment]
I'm getting this error too. What exactly did you do to solve this?

**Comment by besedi** [comment]
Hi, all! anyone know the answer or direction where I can investigate same Error?

**Comment by besedi** [comment]
@r2dseu @FreddieOliveira Hi, all! I have the same issue.
Does anyone know the answer or direction where I can investigate same Error?

**Comment by besedi** [comment]
For information: the problem with server settings, it returns NOT json answer

**Comment by stefanamaerz** [comment]
i had this error today. I reread the docs turns out I had the api endpoint wrong (I am using fleetdm). It seems this error means osquery cannot parse the config json. Not sure if there is no json returned to parse or if it is just of the wrong structure. In either case your the TLS server is not returning what osquery is expecting it to.


Here is what I needed (I had the wrong tls endpoint):
```
--config_plugin=tls
--config_tls_endpoint=/api/osquery/config
```

see for docs here: https://fleetdm.com/docs/using-fleet/enroll-hosts#configure-and-launch-osquery


these two cli flags are somewhat helpful to pass to `osqueryd` for debugging purposes. The latter will show you the json object that osquery has received, however I found it does not print anything if the json object is invalid which really limits its utility as a debugging tool:
```

    --config_check                                        Check the format of an osquery config and exit
    --config_dump                                         Dump the contents of the configuration, then exit
```

hope this helps anyone in the future looking for a solution!
