### ISSUE TITLE
Lost non-blocking connect socket event

### ISSUE THREAD

**Issue by jax777** [osquery/osquery#6609]
[https://github.com/osquery/osquery/blob/master/osquery/events/linux/auditeventpublisher.cpp#L180](https://github.com/osquery/osquery/blob/master/osquery/events/linux/auditeventpublisher.cpp#L180)

// By discarding this event, we will also automatically discard any other
      // attached record

this would lost  Non-blocking  connect event

when we use Non-blocking connect, audit would give us success=no,exit =115,which the auditeventpublisher discarding this event
```
import socket
sock = socket.socket()
sock.setblocking(False)
sock.connect(('www.google.com',443))
```

maybe， we need to judge the non-blocking call separately

**Comment by theopolis** [comment]
Heads up @alessandrogario

**Comment by alessandrogario** [comment]
I think it makes sense to track them in the table; I actually had a branch where this was implemented but I can't seem to find it anymore.

When dealing with non-blocking sockets, Audit will report the applicable syscalls as failed with an error code specifying errno values such as `EINPROGRESS`. Since there is no way for osquery to follow up on what happened on that socket operation, it has no way to tell whether that connection ultimately succeeded or not. For this reason, I would update the schema and introduce an additional `state` column, containing one of the following three values:

1. Definitely succeeded
2. Definitely failed
3. Unknown (no definite error, we last saw it as 'in progress')

This additional feature can also be moved behind a flag (opt-in or opt-out), depending on what the community prefers

**Comment by darkarnium** [comment]
Hey there,

I've spent a few days tracking down some "missing" `socket_events` which I would have expected to have been logged. When debugging the issue I was finding this same behaviour; `connect` (`syscall=42`) audit events were being received by osquery over the audit socket, but were not making it into the table. These "dropped" events had the `error` is set to `-115` (`EINPROGRESS`) with `success=no`, much in the same way as @jax777 describes here.

Perhaps more concerningly it appears that Golang is setting `SOCK_NONBLOCK` [by default](https://github.com/golang/go/blob/f448cb8ba83be1055cc73101e0c217c2a503c8ad/src/net/sock_cloexec.go#L22) when creating new sockets.

I may be incorrect here, but it appears that TCP network connections originating from Go binaries will not make it into the `socket_events` table due to this `SOCK_NONBLOCK` default in Golang?

Having the ability to track these sockets in some form would definitely be welcomed in this case! :)
