### ISSUE TITLE
EC2 Instance Metadata doesn't seem to work for AWS Logging on Windows

### ISSUE THREAD

**Issue by nyanshak** [osquery/osquery#6674]
:wave: 

The [AWS logging docs](https://osquery.readthedocs.io/en/stable/deployment/aws-logging/) give an order for how credentials are pulled for AWS logging. However, from my testing, it seems as if (5) "Profile from the EC2 Instance Metadata Service" doesn't work on Windows.

This seems related but not the exact issue as https://github.com/osquery/osquery/issues/6149.

Request:

Support ec2 instance metadata service as a source of credentials for AWS logging in Windows.

**Comment by theopolis** [comment]
Heads up that I think this is a feature request. I do not think this form of authentication works on macOS or Linux either.

**Comment by nyanshak** [comment]
On Linux EC2, I have been able to use IAM roles associated with the instance with the aws_sts_arn_role, to assume the role in the flag, and to write to Kinesis, without having to specify access keys / secrets.

I don't think this is an entirely new feature but rather extending platform support for this feature across all platforms. Edited the title to reflect other work on macOS / Windows.

**Comment by mike-myers-tob** [comment]
After talking with @nyanshak about the issue, I'm going to remove macOS from the title here. AWS doesn't currently offer EC2 instances running macOS, which may be because EC2 infrastructure is all virtual machines on commodity hardware, but Apple doesn't license macOS to run on non-Apple hardware.

It was noted though, that Windows support for this table might've been commented out due to an [instability in the aws-sdk-cpp dependency](https://github.com/aws/aws-sdk-cpp/issues/901). We ought to see if that instability is fixed, [update the dependency](https://github.com/osquery/osquery/tree/master/libraries/cmake/source/aws-sdk-cpp), and restore [the skipped code in Windows builds](https://github.com/osquery/osquery/blob/master/osquery/utils/aws/aws_util.cpp#L308-L313).

**Comment by mike-myers-tob** [comment]
Closed by the series of PRs https://github.com/osquery/osquery/pull/6756 and https://github.com/osquery/osquery/pull/6754 and https://github.com/osquery/osquery/pull/6749
