### ISSUE TITLE
Windows "drivers" table is incomplete - only includes device drivers

### ISSUE THREAD

**Issue by clong** [osquery/osquery#6852]
# Bug report

### What operating system and version are you using?

```
+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.18362 | 18362 | windows  |
+------------+-------+----------+
```

### What version of osquery are you using?

```
+---------+
| version |
+---------+
| 4.5.1   |
+---------+
```

### What steps did you take to reproduce the issue?

1. Run mimikatz and load the accompanying `mimidrv.sys` driver via `.\mimikatz.exe "!+"`
![image](https://user-images.githubusercontent.com/5092699/103163292-3d68e480-47b1-11eb-9acb-f40d47ba702a.png)

2. Run `select * from drivers` and search for `mimidrv.sys` (it wasn't there)

3. Run `driverquery /q | findstr "mimidrv"`
![image](https://user-images.githubusercontent.com/5092699/103163353-f0394280-47b1-11eb-9246-748d94c1c79f.png)

4. At this time, I noticed that driverview contains quite a few values that the osquery `drivers` table does not

### What did you expect to see?

I expected to be able to see the presence of a loaded kernel driver (mimisys.drv)

### What did you see instead?

I believe the API being used (discussed [here](https://osquery.slack.com/archives/C0FHNQ2N6/p1605233939110900) in slack) only includes device drivers. This leads to an incomplete dataset and blindspots when attempting to detect malicious kernel extensions.

**Comment by manurautela** [comment]
Not sure if this has been addressed but this information should be fetched from **services** table instead of **drivers**.

As mimikatz driver is installed as service.
https://github.com/gentilkiwi/mimikatz/blob/e10bde5b16b747dc09ca5146f93f2beaf74dd17a/modules/kull_m_service.c#L138

However current implementation of windows services table, doesn't fetch information about all kinds of services.

https://github.com/osquery/osquery/blob/001aa5622a1a49b5b048690fae354101f88b1121/osquery/tables/system/windows/services.cpp#L165

Here we pass only **SERVICE_WIN32** , which doesn't include drivers and other kinds of services that might be there on the system.

From that perspective the services table is missing out on a lot of information, not just drivers.

Just for experimentation, i tweaked the code adding other flags based on windows version.
Here is what it shows with mimikatz installed on the test machine.

![image](https://user-images.githubusercontent.com/1333906/109303245-89dba980-7860-11eb-915b-8a6d99d89310.png)

```diff
const std::map<int, std::string> kServiceType = {
+    {0x00000001, "Driver"},
+    {0x00000002, "FS driver"},
     {0x00000010, "OWN_PROCESS"},
     {0x00000020, "SHARE_PROCESS"},
     {0x00000100, "INTERACTIVE_PROCESS"},
     {0x00000110, "OWN_PROCESS(Interactive)"},
-    {0x00000120, "SHARE_PROCESS(Interactive)"}};
+    {0x00000120, "SHARE_PROCESS(Interactive)"},
+    {0x00000050, "USER_OWN_PROCESS"},
+    {0x000000d0, "USER_OWN_PROCESS(Instance)"},
+    {0x00000060, "USER_SHARE_PROCESS"},
+    {0x000000e0, "USER_SHARE_PROCESS(Instance)"},
+    {0x00000210, "PACKAGE_OWN_PROCESS"},
+    {0x00000220, "PACKAGE_SHARE_PROCESS"}
+};

+static inline ULONG getServiceType() {
+    ULONG serviceType;
+
+    // Use version helper api instead os GetVersionEx(..) (deprecated)
+    if (IsWindows10OrGreater()) {
+        serviceType = SERVICE_TYPE_ALL;
+    } else {
+        serviceType = SERVICE_DRIVER | SERVICE_WIN32;
+    }
+
+    return serviceType;
+}
+

+
+  // Deduce service type to be used based on the operating system version.
+  // Across diff versions of windows, new service types have been introduced
+  // and calling api with correct set of flags is required.
+  ULONG serviceType = getServiceType();
+
   DWORD bytesNeeded;
   DWORD serviceCount;
   (void)EnumServicesStatusEx(scmHandle.get(),
                              SC_ENUM_PROCESS_INFO,
-                             SERVICE_WIN32,
+                             serviceType,
                              SERVICE_STATE_ALL,
                              nullptr,
                              0,
@@ -183,7 +348,7 @@ static inline Status getServices(QueryData& results) {

   auto ret = EnumServicesStatusEx(scmHandle.get(),
                                   SC_ENUM_PROCESS_INFO,
-                                  SERVICE_WIN32,
+                                  serviceType,
                                   SERVICE_STATE_ALL,
                                   (LPBYTE)lpSvcBuf.get(),
                                   bytesNeeded,
```

This should make services table more robust including details for services of all types supported in the specific windows.

**Comment by clong** [comment]
Maybe this points to a bigger issue, which is that multiple driver types exist on Windows. Having a table called "drivers" that is really only polling device drivers and not other drivers (like kernel drivers, for example) makes me feel like the table name is slightly misleading. 

@manurautela This is a bit out of my wheelhouse, but are there other methods that exist to load kernel drivers aside from services?

**Comment by manurautela** [comment]
@clong  the way to think about is that "services" key in the registry is just a common placeholder for various kinds of drivers including services (user mode) of diff kinds.

These drivers may fall into further categories broadly software and hardware drivers.
Software only drivers that don't manage any specific physical hardware. e.g. driver for process hacker tool.
```
osquery> select * from services where name like "%kprocess%";
             name = KProcessHacker3
     service_type = Driver
     display_name = KProcessHacker3
           status = RUNNING
              pid = 0
       start_type = DISABLED
  win32_exit_code = 0
service_exit_code = 0
             path = \??\C:\Program Files\Process Hacker\kprocesshacker.sys
```

Whereas the drivers for various kinds of  devices(peripherals) that are physically connected to our machine listed in drivers table.
````
   device_id = HDAUDIO\FUNC_01&VEN_10DE&DEV_0072&SUBSYS_10438528&REV_1001\5&D3FE852&0&0001
 device_name = NVIDIA High Definition Audio
       image = C:\WINDOWS\system32
 description = NVIDIA High Definition Audio
     service = NVHDA
 service_key = HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NVHDA
     version = 1.3.38.40
         inf = C:\WINDOWS\System32\DriverStore\FileRepository\nvhda.inf_amd64_604640e8f3663afb\nvhda.inf
       class = MEDIA
    provider = NVIDIA Corporation
manufacturer = Microsoft
  driver_key = HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e96c-e325-11ce-bfc1-08002be10318}\0000
        date = 1602806400
      signed = 1
```
The installation mechanism for physical devices may includes bunch of other configurations and keys under registry. But services being also one of them. Generally INF files are used to install and configure such devices.

[https://docs.microsoft.com/en-us/windows-hardware/drivers/install/hklm-system-currentcontrolset-services-registry-tree](url)

Officially these are the only mechanism to install various kinds of drivers. Hence  "services" will have entries for both types of drivers. But the information being fetched might be diff.  Since drivers for actual physical devices will have additional information that we are fetching in the table as of today.

**Comment by clong** [comment]
@manurautela thanks for the explanation - that helps me conceptualize it much more clearly! Just for clarification, are you submitting a PR with the changes listed in your diff above or was that just for testing purposes?

**Comment by manurautela** [comment]
@clong  i will check code contributing guidelines and get back.

**Comment by joshdhart** [comment]
Just came across this lack of visibility for "KERNEL_DRIVER" type services in osquery as well. 

@manurautela, did this ever go anywhere in pushing an MR w/ your changes that pulls the additional Service Types?
