### ISSUE TITLE
Can't query windows_eventlog

### ISSUE THREAD

**Issue by ordin2342** [osquery/osquery#6968]
`SELECT data FROM windows_eventlog WHERE channel = "Security";`

`W0225 19:52:30.968338  3204 windows_eventlog.cpp:293] Failed to search event log for query with 5`

I went quite a way (over 2 weeks) to setup fleet and enable windows events and powershell events in a Windows 10 Home. There's no more errors, but I still can't query those. Powershell table is always empty, windows table gives above error. Other tables work fine.

Is there a complete guide for noobs how to enable and use windows event logs?

**Comment by ordin2342** [comment]
Update: After more fiddling with configs (basically guessing config settings by reading other, unrelated github issues) I made some more progress and can query now system events. The issue looks now like this:
`W0225 20:43:33.469908  1568 windowseventlogpublisher.cpp:129] Failed to subscribe to security: 5`

**Comment by clong** [comment]
Are you running osquery as admin when trying this? The `failed to subscribe` message sounds like it could be a permissions issue

**Comment by manurautela** [comment]
```
ERROR_ACCESS_DENIED
5 (0x5)
```
[https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-]

As pointed previously you seem to have permissions issue. 

osquery won't go fix the security/permissions or misconfiguration issues on it's own. If the machine is misconfigured in some way or say needed service is not available.  Then it needs to be fixed so that osquery can integrate and fetch needed information.

**Comment by theopolis** [comment]
Let us know if running as an admin does not solve the issue, and we can investigate further.
