### ISSUE TITLE
Empty kernel_panics table after macOS 10.15

### ISSUE THREAD

**Issue by alameenshah** [osquery/osquery#7215]
# Bug report
Looks like Osquery is not able to find and parse the kernel panic logs correctly in macOS 11.4.

### What operating system and version are you using?
version = 11.4
build = 20F71
platform = darwin

### What version of osquery are you using?
version = 4.9.0

### What steps did you take to reproduce the issue?
Trigger a Kernel Panic on a Mac machine (with macOS 11.4 installed.)
1. Reboot into software recovery mode. Disable SIP - `csrutil disable`
2. Reboot again.
3. Run - `sudo dtrace -w -n "BEGIN{ panic();}"`

### What did you expect to see?
`osqueryi --line "SELECT * from kernel_panics;"` shows kernel panics information.

### What did you see instead?
The query returns empty. 

I'm able to see the panic log files in this directory - `/Library/Logs/DiagnosticReports/ProxiedDevice-Bridge`. The file names are like `panic-full-2021-07-28-142855.0003.ips`.

**Comment by puffyCid** [comment]
Hi, just to confirm is this an actual kernel panic log file?
Looking at the `kernel_panics` table it looks like osquery is looking for files with the extension `.panic` in `/Library/Logs/DiagnosticReports/`.  
Do you know if new macOS systems use a new kernel log format and log kernel info to `panic-full-<date>.ips` files?  
I did some quick searches and I could not find any definitive answers. It looks like kernel panics are  still logged to `.panic` files?

Looking at `panic-full-<date>.ips` on my macOS system it looks a bit related to BridgeOS logging?

**Comment by alameenshah** [comment]
Using the same steps (as described above) on macOS 10.15, kernel panics seem to be creating .panic files immediately under `/Library/Logs/DiagnosticReports` directory. So I'm guessing `.ips` files inside `/Library/Logs/DiagnosticReports/ProxiedDevice-Bridge` directory to probably be new behavior in macOS 11.x. 

Also found a python parser for `.ips` files [here](https://gist.github.com/PsychoTea/7ac675e6dda0c1c8eb8feaaa71fb0c88). It is able to fetch panic information from `.ips` files.

```
python3 PanicParser.py /Library/Logs/DiagnosticReports/panic-full-2021-07-28-142855.0003.ips
panic(cpu 1 caller 0xfffffff007f5c190): macOS panic detected
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 18P4663
macOS version: 20F71
Kernel version: Darwin Kernel Version 20.5.0: Fri May  7 22:04:14 PDT 2021; root:xnu-7195.121.3~8/RELEASE_ARM64_T8010
Kernel UUID: 873F4AC5-B66C-3016-8EAC-39D538EEB5A3
iBoot version: iBoot-6723.120.36
secure boot?: YES
x86 EFI Boot State: 0xd
x86 System State: 0x0
x86 Power State: 0x0
x86 Shutdown Cause: 0x1
x86 Previous Power Transitions: 0x405060400
PCIeUp link state: 0x89271614
Paniclog version: 13
Kernel slide:      0x000000001e3a4000
Kernel text base:  0xfffffff0253a8000
mach_absolute_time: 0x40fcfa38d28f
Epoch Time:        sec       usec
  Boot    : 0x60cc181a 0x0004f05f
  Sleep   : 0x610167c7 0x0002ea46
  Wake    : 0x610167c7 0x0003e047
  Calendar: 0x61016991 0x000f2474

Panicked task 0xffffffe199fec630: 3852 pages, 227 threads: pid 0: kernel_task
Panicked thread: 0xffffffe19a1cc800, backtrace: 0xffffffe8047b3700, tid: 427
		  lr: 0xfffffff00774f49c  fp: 0xffffffe8047b3750
		  lr: 0xfffffff00774f2f4  fp: 0xffffffe8047b37c0
		  lr: 0xfffffff00787adf0  fp: 0xffffffe8047b3890
		  lr: 0xfffffff007d755fc  fp: 0xffffffe8047b38a0
		  lr: 0xfffffff00774f028  fp: 0xffffffe8047b3c20
		  lr: 0xfffffff00774f028  fp: 0xffffffe8047b3c80
		  lr: 0xfffffff00877f200  fp: 0xffffffe8047b3ca0
		  lr: 0xfffffff007f5c190  fp: 0xffffffe8047b3cd0
		  lr: 0xfffffff007f4a520  fp: 0xffffffe8047b3d30
		  lr: 0xfffffff007f4c41c  fp: 0xffffffe8047b3dc0
		  lr: 0xfffffff007f49bc4  fp: 0xffffffe8047b3e50
		  lr: 0xfffffff007e4e814  fp: 0xffffffe8047b3e80
		  lr: 0xfffffff007cca010  fp: 0xffffffe8047b3ec0
		  lr: 0xfffffff007cc9890  fp: 0xffffffe8047b3f00
		  lr: 0xfffffff007d805a0  fp: 0x000000000000000
```

**Comment by mike-myers-tob** [comment]
Confirmed that this is an issue, and in osquery 5.2.x. The format of the crash file might have changed _again_ because it is now once again in the directory `/Library/Logs/DiagnosticReports/` with the `panic` file extension. E.g., `/Library/Logs/DiagnosticReports/Kernel-2022-05-05-173858.panic`.

The parser script that @alameenshah found is almost correct, but now the JSON object is named `macOSPanicString`, not `panicString`. Otherwise it works.

It looks like this table would work for macOS 10.something up through 10.15, and then there might have been a change with macOS 11 and another smaller change with macOS 12. It's annoying but, the file is a simple JSON file in a directory owned by root so it seems worth just updating the table to parse out the values again.

That said, the table should be tested _again_ on ARM, because there's registers and architecture-specific stuff in the strings to be parsed.

FYI, if anyone is using a VMware Fusion VM of Monterey, to boot into Recovery Mode it is easiest if you set the Startup Disk to the `Install macOS Monterey` install media and reboot, rather than messing around with try to boot the Recovery partition.

**Comment by mike-myers-tob** [comment]
For reference, here is a sample kernel panic file from a macOS 12.3.1 host
[Kernel-2022-05-05-173858_macOS_12.3.1.panic.zip](https://github.com/osquery/osquery/files/8775382/Kernel-2022-05-05-173858_macOS_12.3.1.panic.zip)
.
