### ISSUE TITLE
Cross-compilation and Universal Binary on macOS

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7223]
To support Apple Silicon "fat" binaries (Universal Binaries), we should investigate what is required at the packaging and code-signing levels, possibly affecting https://github.com/osquery/osquery-codesign and https://github.com/osquery/osquery-packaging

Ref: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

This task may be blocked by the task of porting all of osquery's third-party dependencies in order to successfully build for Apple Silicon.

**Comment by packetzero** [comment]
Yes, all the third-party deps will need to be compiled for same architecture flags.
For main repo, just need to add `set(CMAKE_OSX_ARCHITECTURES $(ARCHS_STANDARD))` and with Xcode 12 or better, will cross-compile and build the universal binary.
I had an issue with some third-party libraries not recognizing the `ARCHS_STANDARD`, and had to specify `CMAKE_OSX_ARCHITECTURES=x86_64;arm64` instead.

**Comment by directionless** [comment]
If we do this outside cmake, the process is to gather the binaries and to use the `lipo` command line tool to generate a universal binary. Obviously this requires having those both built ahead of time. 

I'm not familiar with the cmake options.

**Comment by Smjert** [comment]
> If we do this outside cmake, the process is to gather the binaries and to use the `lipo` command line tool to generate a universal binary. Obviously this requires having those both built ahead of time.
> 
> I'm not familiar with the cmake options.

The CMake option is the one @packetzero is talking about and it should simply call `lipo` automatically for you (along with compiling osquery for the two architectures).

Just to clarify something I've said during the last office hours, I was slightly confusing a couple of issues.
CMake can be used, in the `osquery/osquery` project at least, because it already deals with the builds and stitching for you (bar any other specific osquery project/CMake interactions issues).
Also it's unlikely that between macOS x86 and macOS M1 we need two different versions of a third party library (to have M1 support and also support the oldest macOS x86 we want to support), I was actually thinking of macOS in general vs Linux; so this won't affect the ability to use the CMake option to do everything in one run.

**Comment by directionless** [comment]
I think y'all merged this, yes?
