### ISSUE TITLE
Update smartmontools to build natively on Apple Silicon

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7241]
Background:

Building osquery natively on Apple silicon is primarily a matter of building all of its third-party dependencies (and consequently all of their dependencies) natively on Apple silicon, using the osquery toolchain and CMake-based build.

**Comment by Smjert** [comment]
We are not going to port this library; the smart table is based on a custom library that has been built on top of the smartmontools code, by refactoring it and adding a library interface, since smartmontools doesn't actually provide a library.

Such custom code is not updated anymore by the original author and updating it is not an immediate task.
Moreover the library and so the table was only supporting the SATA protocol, which doesn't work with nvme disks.
