### ISSUE TITLE
Add a GitHub Actions CI runner for macOS Big Sur

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7325]
# Task

[Recently GitHub Actions added a runner for macOS 11](https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/). To better test that there are no issues specific to version 11.x and higher (like #7321 etc), we should consider adding this to our CI workflows. The packaging and signing doesn't have to change, as long as it can rely on the 10.15 runners.

Depends on #7320

**Comment by Smjert** [comment]
An update for this task: the idea here is actually to update all current 10.15 instances to 11.x, included the packaging/signing workflow.
The M1 port and the relative x86 updated libraries are already re-configured and tested under Big Sur.
Beyond that, I don't believe that the packaging or signing are hardly tied to an OS version, so updating should be easy; at the same time though, since some packaging already happens on the `osquery/osquery` repo, that will use Big Sur anyway.

Ideally, together with the M1 port, we will keep:
- 2 Big Sur x86 instances, one Release and one Debug to build and run tests. The Release one will also build the package data and unsigned packages as usual.
- 1 Big Sur x86 instance which will build in Release mode targeting M1. This will also generate a package data and an unsigned package
- 1 Catalina x86 instance, to run both Release and Debug tests only, built on the Big Sur x86 VMs

So we will end up with 2 additional VMs but that will do less work than the normal jobs.
