### ISSUE TITLE
No results in the python_packages table on Windows

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7350]
# Bug report

### What operating system and version are you using?

+------------+-------+----------+
| version    | build | platform |
+------------+-------+----------+
| 10.0.19043 | 19043 | windows  |
+------------+-------+----------+

### What version of osquery are you using?

osquery 5.0.1

### What steps did you take to reproduce the issue?

Have only one version of Python installed, which should not to be installed for all users,
so basically not under `C:\Program Files` but `C:\Users\<user>\AppData\Local`.

Run the query `select * from python_packages` from an Administrator shell.

### What did you expect to see?

A list of packages

### What did you see instead?

No result

From my quick debug: we use registry keys on Windows to find the installation paths; we search for `HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\%\\InstallPath` and `HKEY_USERS\\%\\SOFTWARE\\Python\\PythonCore\\%\\InstallPath`

When Python is installed like previously said, then it will be only present under the `HKEY_USERS` key.
Debugging I saw that it succeeds expanding the first `%`, which results in a list of keys to explore, each for a user. But then when it comes to the correct user and when it tries to do the second expansion (which should contain the version), it fails here: https://github.com/osquery/osquery/blob/3795ab0785c067fd09164fab8ddbd3a0d73c256c/osquery/tables/system/windows/registry.cpp#L511-L514

**Comment by iko1** [comment]
@Smjert, I've found the bug. Please review my PR. I found that code passed the WinAPI library call registry key to fetch but the RegOpenKeyExW can return error in various results, The trivial one is when the key doesn't exist in the registry, and it's exactly what it's our case when writing glob wildcard like this one: HKEY_USERS\\%\\SOFTWARE\\Python\\PythonCore\\%\\InstallPath

I handle that result code in order to make sure that populateSubkeys doesn't return error for case that i explained above.

**Comment by iko1** [comment]
@mike-myers-tob, I think you can close this issue after the fix was merged..
