### ISSUE TITLE
Easier way to tell which tables are available on a platform

### ISSUE THREAD

**Issue by jerkstorecaller** [osquery/osquery#7369]
# Feature request

### What new feature do you want?

Make it more clear to the user which table is available on which platform.

I was trying to figure out how to list partition info and their usage/capacity to on Linux ("df -h" basically), and learned the bad way that the tables "disk_info" and "logical_drive" are exclusive to Windows. I was about to submit a bug report that disk_info was missing on Linux. Then by looking at the schemas at https://osquery.io/schema/5.0.1 , I hovered over the "Improve this description" link, and saw that the URL contained /windows/ in the path. Didn't even notice the Windows icon in the top right until 5 minutes into writing this ticket.

1) I think it would be nice if the doc provided a filter view to only show a desired platform, instead of showing them all 277 tables, half of which aren't usable.

2) Also I think platform exclusive tables shouldn't be given generic names like "disk_info" which you'd expect to apply to all platforms. For example:

* disk_info -> windows_disk_info (until the day disk_info is crossplatform)
* programs -> windows_programs

But "registry" is ok to leave as "registry" since that only exists on Windows.

3) This depends on the person probably, the OS icons on the schema page might be preferable to others, but I think if the text showed "Windows | Darwin | Linux" instead of picture icons, it would be better. I guess I'm just trained to mentally filter out images as pointless info due to how modern websites are designed.

### How is this new feature useful?

Helps users more easily realize which tables are available for a given platform.

**Comment by Smjert** [comment]
1. If you mean the schema page, that has already a filter. On the top center of the page, on the right of the tables list you have "Show only Tables compatible with:" and an arrow to open a dropdown.

2. I "think" the reason here is to avoid having multiple names in the history of the same table; meaning you might start with a table that's implemented on Linux and macOS (what prefix to put?), but it can eventually be implemented on Windows, but it isn't yet.
We can alias table names but the schema list shows their main name only.

3. It doesn't bother me, but I'm also not a designer :).

**Comment by directionless** [comment]
Thank you for the suggestion, but I think we want to avoid having platform specifics in the table names. 

In addition to the filtering @Smjert describes, the table descriptions also include a platform icon in the top right.
