### ISSUE TITLE
(Meta) Instructions for Slack usage?

### ISSUE THREAD

**Issue by jerkstorecaller** [osquery/osquery#7393]
I had a usage question, and the Github template says to ask questions on Slack. I just spent almost an hour trying to join osquery.slack.com and failed.

I've never used Slack before, so I signed up, installed the desktop application, created my personal workspace, etc. 

**Attempt 1**
I opened osquery.slack.com in the browser, entered my Slack email and password, and it says "Sorry, you entered an incorrect email address or password."

**Attempt 2**
I looked all over the desktop application, and see no way to join osquery.slack.com. I tried clicking + then Sign In to Another Workspace. It opens my browser, I get prompted for my email, it takes me to a page where I gotta input a code, Slack emails me the code, I paste it, and...I'm now staring at a list of just my own workspace, with no way to add a new workspace like osquery.slack.com. 

**Attempt 3**
I also tried +, then Find Workspaces. That takes me through the same procedure as attempt 2, and at the end I'm staring at the same page as before, just a list of my own workspace.

I read the Slack getting started guide and they don't say anything new. 

I'm thinking maybe osquery.slack.com was accidentally configured to not accept public members? Either that, or Slack is the most ~~terrible~~ complex chat app ever conceived. 

Can you please explain, like you would to a child, how people can join your Slack?

**Comment by Smjert** [comment]
Hello @jerkstorecaller, at the top of our github project homepage (https://github.com/osquery/osquery#readme) or also at the bottom of the osquery website main page (https://osquery.io/), we have a link to request an autoinvite, copied here for convenience: https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw

For each workspace you join, you need to have a separate account, so that link should take you to the creation of a new one.

Finally I'm not a workspace admin but I believe Slack is invite only, with some allowlisting for some domains if you want (https://slack.com/help/articles/115004856503-Manage-how-people-join-your-workspace)

**Comment by jerkstorecaller** [comment]
Thank you, I was able to join!  I had no idea about requiring an invite, I just used the link given in the new issue template, which is https://osquery.slack.com which sends you nowhere if you didn't already join the slack.

If you don't mind I'll send a PR to update the issue template to add your invite link?
