### ISSUE TITLE
sqlite column names are case insensitive, osquery is not

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7441]
# Bug report

Diagnosing a strange ATC error for someone on slack... They were trying to create a table with a `Path` column. Osquery tries to create a column named `path`. There's a check to make sure there's not an existing `path` column, but because it's case sensitive, it doesn't notice the `Path` column.

And the resultant sqlite create statement  is invalid:
```
CREATE TABLE atc_with_path(`path` TEXT, `Path` TEXT, `Anum` TEXT)
```

I think this is because https://github.com/directionless/osquery/blob/c312e6ed3f18f4ba0c8ec0822adb3e1126bd1a1c/osquery/sql/virtual_sqlite_table.cpp#L64-L69 

I could replace that with an case insentive iterator. But, it seems like this fix belongs in the `count` method. I can't understand `DynamicTableRow` well enough to add it

### What version of osquery are you using?

5.1

**Comment by Smjert** [comment]
Nice catch!
The `count()` function comes from `std::map`, so it's using the hash of the string to find the value, so it's not possible to do a case insensitive search.
Since the columns are added in the previous loop, I would check here, with a case insensitive check, if a column with the name `path` is found, if so set a boolean
https://github.com/osquery/osquery/blob/e8e325cea15c41c43cc1b088a851f72d4d1c6a14/osquery/sql/virtual_sqlite_table.cpp#L43

Which is the checked later, to decide what to do.
