### ISSUE TITLE
WmiRequest should follow RAII principles to avoid crashes

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#7448]
This is mostly to keep track of the issue, I haven't spent much time analyzing it.

The WmiRequest class could use a slight refactor since its constructor its doing quite a lot of work (initializing, connecting, running a query) and can end up in an unknown state if errors happen during construction.

An example is if the ConnectServer fails for some reason:
https://github.com/osquery/osquery/blob/9ecb3f0a77566e7cbc9683b1277a78b25efe1483/osquery/core/windows/wmi.cpp#L394-L401

Then `services_` is not set and will remain a nullptr.
If then the user of the class later calls the public method `ExecMethod`, then a crash will happen:
https://github.com/osquery/osquery/blob/9ecb3f0a77566e7cbc9683b1277a78b25efe1483/osquery/core/windows/wmi.cpp#L441-L458

Instead of just returning, the construction should fail with an exception.

Moreover I would suggest to move the execution of the query out of the constructor and on a separate function, much like the `ExecMethod`.
This way it's also possible to better distinguish what has failed.

**Comment by josephsweeney** [comment]
In my experience writing C++, I have never used exceptions (they were literally not allowed) so we also had the problem of how to handle constructing objects where failure can happen in the constructor. The pattern we used that was simple and reliable was to have the constructor only include setup operations that are not able to fail. Then you implement a static factory method to add all the values that can fail. This then allows you to actually return error values so the caller knows that construction of the object was unsuccessful and can behave appropriately. I find this pattern is simple and construction remains intuitive.

Would this solution be acceptable for this problem? Do you foresee any problems with this approach?

**Comment by josephsweeney** [comment]
Despite lack of restrictions, I would argue that use of exceptions for error handling is harder to reason about than simple return values. That being said, sometimes following the convention of the existing code is more important so I will defer to you.

With regards to your concerns:

1. When using static factory methods (which just to be clear, just means putting the constructor logic in a static method on the class like `static StatusOr<WmiRequest> WmiRequest::CreateWmiRequest(...)`) you simply make the constructors private so that creation must go through the factory method. That way invalid initialization results either in an error or a valid object. I would argue using exceptions is more likely to cause a crash because the caller can write code that fails to catch the exception and would therefore have an invalid `WmiRequest` but not realize they wrote incorrect code until an error actually occurs at runtime. Using a static factory method means the caller knows they must handle a failure case because the resulting value must be extracted from the `StatusOr<WmiRequest>`.
2. This method gets you exactly that, the creator of the `WmiRequest` will necessarily know whether or not it was successful because they called `WmiRequest::CreateWmiRequest`.

I would be happy to type up the proposed solution as it is fairly simple so you can see how small of a change it actually is if you'd like.

**Comment by josephsweeney** [comment]
Ahh, I see the problem is that `Expected` doesn't behave as I would want it to. I'm expecting semantics like [absl::StatusOr](https://abseil.io/docs/cpp/guides/status#returning-a-status-or-a-value) where you have to check to make sure there was no error to get the return value. 

This could probably either be added in a new `StatusOr` object with basic functionality, or implemented another way (`static Status WmiRequest::CreateWmiRequest(..., WmiRequest* result)`).

**Comment by Smjert** [comment]
> Ahh, I see the problem is that `Expected` doesn't behave as I would want it to. I'm expecting semantics like [absl::StatusOr](https://abseil.io/docs/cpp/guides/status#returning-a-status-or-a-value) where you have to check to make sure there was no error to get the return value.

Maybe I'm missing something but you have to check for an error too in `Expected`, otherwise if you attempt to get the value and it's not a value, you get an exception from the underlying variant.
Isn't it the same with StatusOr? If you don't check for `ok()`, nothing is preventing you to dereference it and get an exception right?

**Comment by josephsweeney** [comment]
I see, I didn't look carefully at `Expected` I guess it does work how I expected. 

The way I think about it is if a function returns an `Expected` (or `StatusOr`) then that communicates to the caller that this function may fail, so they have to deal with either case. If using exceptions, then the return type doesn't communicate to the caller that the function may fail and they have to catch an exception. So I would lean more toward using a static factory method that returns an `Expected` because then the types makes the usage clear. 

With regard to enforcement of checking errors, `StatusOr` had a good method called `ValueOrDie()` which was the way you would conventionally get values out without error checking. This again clearly communicated that the consequences of not error checking meant the code crashed. I think you could just dereference the `StatusOr` too, but the more explicit method was preferred. Generally, code review is the tool to catch problems like this

I'm not really sure where this leaves us with regard to how you would like to solve this issue. I wanted to communicate my experience of a design pattern that generally solves this issue but I am also not dogmatic so I know other solutions will work so I am open to it. 🙂 I may also have misunderstood what you were proposing in the original issue. Was it proposing that the constructor just throws exceptions rather than returning? Or was it that any setup that fails gets moved into a separate method called by the constructor and if that method fails then the constructor throws an exception? Or was it neither and I am way off base?

**Comment by Smjert** [comment]
Sorry for the tangent, I was giving you options and a couple of properties that should've been upholded.

That been said I think a static factory method + the use of Expected could be good.

**Comment by mshingote** [comment]
Also one more thing, with these changes can we avoid cleanup code of most of wmi raw pointers using [CComPtr](https://www.codeproject.com/Articles/10539/Making-WMI-Queries-In-C)?
