### ISSUE TITLE
Using ```"select logon_time from logon_sessions"``` in osqueryi on a Windows machine produces an undecipherable number

### ISSUE THREAD

**Issue by StewAlexander-com** [osquery/osquery#7779]
When I run
----
```
osquery> select logon_time from logon_sessions;
logon_time = 1664464380
```

The output **_1664464380_** is a weird number, my guess from attempting to google it is it is something called a timestamp, is there a way to convert this to a typical _date and time_?

If so is there a way to integrate this into osquery so I can see when someone logged in?

If so that would be highly useful because I use SaltSatck calls to query information from our PC fleet, thanks

**Comment by Smjert** [comment]
Hello @StewAlexander-com, that's a unix timestamp/epoch; osquery tries to show all times in that format because then you can easily transform it with SQL functions.
osquery uses sqlite form of SQL so https://www.sqlite.org/lang_datefunc.html, and specifically:
```
Compute the date and time given a unix timestamp 1092941466, and compensate for your local timezone.

    SELECT datetime(1092941466, 'unixepoch', 'localtime');
```
We also have a Slack where this kind of questions can be asked: https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw

**Comment by StewAlexander-com** [comment]
Hey that's a nifty, well thanks @Smjert 

To bad for all us NON-SQL folks, but then I guess we shouldn't be using OSQuery, ehh?  Anyway, closing
