### ISSUE TITLE
PID reuse can lock the pid file, and cause osquery to exit

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7796]
# Bug report

I don't have full info here, but one of our test devices recently failed to start osquery. Digging through some logs osquery logging about pid file issues, and then exiting. (And then launcher would restart it)

```
E1017 10:00:52.141956 52692352 init.cpp:455] Refusing to kill non-osqueryd process 788
E1017 10:00:52.142223 52692352 init.cpp:506] osqueryd Pidfile check failed: Pidfile::Error::Busy
```

This issues seems to have persisted across reboots. 

I don't know what process 788 was.

Deleting the pid file was a simple fix.

I have not been able to recreate this with simple tests.

**Comment by Smjert** [comment]
I assume this is happening on a Linux machine?

In any case, is it really crashing (causing a core dump, you have a stack trace?) or just exiting?

When that last line is printed, osquery does a shutdown: https://github.com/osquery/osquery/blob/027307903d38161fedd7e5996d0b08adb666df82/osquery/core/init.cpp#L509

It may crash when shutting down; our shutting down logic is still not really robust and so if doing so from an unexpected place, or in a certain, it may cause a crash (due to race conditions or other things).

Back to your issue, I "think" that it would make sense that if we detect pid reuse (as it's saying in the previous log line) we should not terminate osquery, but just accept the pid reuse and overwrite the pidfile.

**Comment by Smjert** [comment]
Actually now that I think again about this issue, even when we change this logic, it is still entirely possible to have a dangerous race condition.
What can happen is that since the check for the process existence and match to a certain pid is separate from the act of killing the process, if it's an osquery process, if the logic finds that an osquery process matching the pid is running, but between that moment and the call of `kill` the process exits and the pid is reused, then we are killing the incorrect process.

I don't think we should keep the `--force` flag, it's not the same as when the watchdog kills its child, because there there's a zombie mechanism that prevents pid reuse, and permits the watchdog to be sure that it's not trying to kill another process.

**Comment by alessandrogario** [comment]
> Actually now that I think again about this issue, even when we change this logic, it is still entirely possible to have a dangerous race condition. What can happen is that since the check for the process existence and match to a certain pid is separate from the act of killing the process, if the logic finds that an osquery process matching the pid is running, but between that moment and the call of `kill` the process exits and the pid is reused, then we are killing the incorrect process.
> 
> I don't think we should keep the `--force` flag, it's not the same as when the watchdog kills its child, because there there's a zombie mechanism that prevents pid reuse, and permits the watchdog to be sure that it's not trying to kill another process.

The `--force` flag was added as a workaround for problems caused by the old pidfile implementation, which was not correctly performing any locking. I agree with @smjert that it should be removed

**Comment by directionless** [comment]
> I assume this is happening on a Linux machine?

macOS

> Back to your issue, I "think" that it would make sense that if we detect pid reuse (as it's saying in the previous log line) we should not terminate osquery, but just accept the pid reuse and overwrite the pidfile

That's my feeling as well -- if we can tell the pid file is stale, then we should just clean it and move on. I don't have opinions about where the race conditions are most likely.

**Comment by y0d4a** [comment]
Hi, is there any update on this?
I got same issue...

**Comment by Smjert** [comment]
> Hi, is there any update on this? I got same issue...

Hello @y0d4a, could you provide some more information?
The precise steps you followed, which flags you provided to osquery etc?


@directionless  Now that I was re-reading this, while `--force` is still bad, I completely missed the fact that for osquery to go and attempt to kill the pid written in the pidfile, it first has to fail locking it.
Which means that if it failed locking it, something else was keeping the lock on it (and unless another process is trying to mess with osquery, that means that it was another osquery process).

So I'm not sure there's actually an issue with osquery detecting that the pidfile is busy; that's the correct part, the issue is more what to do next, meaning that a process, which is not osquery, with sufficient privileges could lock the file instead and if the default behavior is for osquery to stop, than osquery won't start. But this is unlikely, especially since if a process already has such privileges it can do worse.
So I think that `force` should still be removed, but it's correct that osquery stops if it finds the pidfile to be busy.

**Comment by directionless** [comment]
I wonder what was locking it. The machine had rebooted.

**Comment by directionless** [comment]
Not sure. There was probably a crash/restart loop happening

**Comment by Smjert** [comment]
> Not sure. There was probably a crash/restart loop happening

I see; you said that launcher restarts osquery, but I wonder when it decides to do that.
You have to keep into account that if launcher is executing osquery, it's direct child is the watchdog, so if there is a situation when your launcher can restart osquery even if it's still running (for instance because it asked osquery to restart with a SIGINT or SIGTERM but a timeout went off), then the new osqueryd (watchdog) process could create a new osqueryd (worker) process before the previous worker process died.

**Comment by directionless** [comment]
> I see; you said that launcher restarts osquery, but I wonder when it decides to do that.

When osquery stops. And launcher runs it without the watchdog.

**Comment by y0d4a** [comment]
is there news regarding this?
I have same issue on linux and mac os...

**Comment by directionless** [comment]
I bumped into this again today.

**Comment by Smjert** [comment]
Hey @directionless, @y0d4a, the problem here is getting a reproducer. Just take into account that it's not necessarily osquery doing something incorrectly, but correctly preventing multiple instances to be launched.
So we have to have a reproducer that shows that's osquery that's not doing something correctly.

Also, @y0d4a , can you please tell us what's your setup?
Are you also using Kolide launchers in front of osquery?

**Comment by y0d4a** [comment]
hi Smjert, thank you on answer.
For now on system where i had issue, now is gone... not sure what happen, but seems you have right, maybe something call osquery in same time or similar ...

**Comment by Smjert** [comment]
For everyone that is reporting that they are affected by this, please always provide the full information:
1. What osquery version
2. What platform
3. **Which third party software (if any) is launching osquery**
4. Logs from osquery when this happens, possibly with `--verbose` active

It would be ideal if this could be reproduced launching osquery "directly" (via Windows services, systemd, launchd is fine, just not with a third party launcher), otherwise if the launcher is misbehaving, I can definitely see how this can happen, but it's not a problem in osquery.

**Comment by laurathaqi968** [comment]
Dear @Smjert 

Please find the details as following on the Pidfile check failed: Pidfile: :Error::Busy 

wazuh plugin version: 4.x-2023.09.12
wazuh agent version: 4.5.1-1
wazuh app for Kibana manager version:  7.17.9 
osquery version: 5.9.1 

At the beggining, this error was eliminated via the following(https://github.com/wazuh/wazuh/issues/15654): 1. stop the osquery, 2.start the wazuh-agent, 3.start the osquery. However, after restart of the computer, the error is back. It gets fixed with the mentioned approach, but I can't keep doing this manually to every computer, after every restart. 

Can you please support in this issue. 

Thank you,
Laura

**Comment by Smjert** [comment]
@laurathaqi968 So I cannot specifically say how the Wazuh agent expects to work, but reading the issue you linked it seems that you have the osqueryd service that comes with osquery itself enabled **and** the Wazuh agent that tries to launch osquery itself too.

If that's the case there's a reason for it?
One of the two (depending on the requirements of Wazuh) has to be disabled. There are ways to run multiple instances if you want to, but I don't think it's ideal.
In that last case you would have to set (to whatever osquery instance you can control its configuration) a different path for `--pidifile`, `--database_path` and ideally also `--logger_path`.

**Comment by directionless** [comment]
I've started to think this is happening because launcher restarts osquery, and osquery hasn't finished ending and cleaned up before the new one tries to grab the pid file.And while the error is werid. it doesn't feel like a bug

**Comment by Smjert** [comment]
> I've started to think this is happening because launcher restarts osquery, and osquery hasn't finished ending and cleaned up before the new one tries to grab the pid file.And while the error is werid. it doesn't feel like a bug

I would expect the restart to be a SIGTERM or SIGINT against the osquery process, and then the execution of a new osquery process right?
In that case then the launcher should wait for the process to fully exit; in theory as soon as the pid of the process disappears the pidfile lock should be released, therefore if this is the case, it's something that the launcher should fix.

**Comment by directionless** [comment]
I don't have more information, but I think I've convinced myself this is not osquery's fault.
