### ISSUE TITLE
Request -- Yara tables should support `pid_with_namespace`

### ISSUE THREAD

**Issue by directionless** [osquery/osquery#7808]
# Feature request

With the recent OpenSSL disclosure, people are trying to find processes running with vulnerable openssl versions. Akamai released a [blog post](http://akamai.com/blog/security-research/openssl-vulnerability-how-to-effectively-prepare#query) with a yara based rule. This works pretty easily for things on the host OS.

Unfortunately, it does not work so well for containers.

I'm not totally sure what the current state of container support is like, but I think adding `pid_with_namespace` to the yara stuff would be an approach here.

**Comment by NickBorgersOnLowSecurityNode** [comment]
I think the ideal would be that `path` columns in `process` tables gain a companion column `path_on_host` which unwinds any mount namespace the process is running in and resolves where the file the process accessed on its view of the filesystem actually exists on the host.

I can see this existing in each of these tables:
- [`process_events `](https://osquery.io/schema/5.5.1/#process_events)
- [`process_file_events `](https://osquery.io/schema/5.5.1/#process_file_events)
- [`process_memory_map `](https://osquery.io/schema/5.5.1/#process_memory_map)
- [`process_open_files `](https://osquery.io/schema/5.5.1/#process_open_files)
- [`process_open_sockets `](https://osquery.io/schema/5.5.1/#process_open_sockets)

My basis for this is that if I'm inspecting a process from the host's perspective I would want to take any follow up or reporting action from the "host" perspective. The path from within the mount namespace is important and potentially useful, but for a lot of actions I would do with information about a process I would need to act from the host's perspective. 

As an engineer trying to determine if I'm using a particular binary or DLL anywhere in my environment
I want to be able to target `osquery` at the files processes have loaded into memory by their path on the host filesystem
So that I can use `osquery` to run my yara rule against all binaries and DLLs running on Linux hosts

Another alternative approach would be for osquery to spin up processes in the mount namespace of a target processes using `nsenter`, but I expect the complexity of that would be explosive.

I also wonder if `partner_pid` in [`process_open_pipes`](https://osquery.io/schema/5.5.1/#process_open_pipes) should include a companion for processed that are running in a PID namespace.

**Comment by NickBorgersOnLowSecurityNode** [comment]
I am trying to work on fixing this as a low priority work item. I have hit a snag on dependency resolution that I think is driven by ignorance on either C++ project builds in general or osquery builds in particular. Any advice would be appreciated.
https://github.com/NickBorgersOnLowSecurityNode/osquery/pull/2
