### ISSUE TITLE
How to get the process % cpu utilisation ?

### ISSUE THREAD

**Issue by sourabhsrawat** [osquery/osquery#7828]
Hi, 
I am trying to find the % CPU utilization of a process, in the process table only getting the time in user and kernel mode.
Can you please help me with the correct query?

**Comment by Smjert** [comment]
Hello @sourabhsrawat, there's currently no ready CPU % for processes in any table. The % has to be calculated on the log collector side, using two samples of the processes rows, taken at a certain interval.

The following PR will add the ability to get a CPU usage: https://github.com/osquery/osquery/pull/7597

**Comment by sourabhsrawat** [comment]
@Smjert Thanks for your response,  do you have any example of how to calculate it from the log collector?

**Comment by Smjert** [comment]
> @Smjert Thanks for your response, do you have any example of how to calculate it from the log collector?

With log collector I mean anything in the backend that osquery ships logs to. So that depends on what you use.

Suppose you are using the following distributed query, where `1936` is a known pid of a process you want to monitor:
```
SELECT strftime('%s', 'now') as time, pid, name, user_time, system_time, (user_time + system_time) as total_time FROM processes WHERE pid = 1936;
```

If you do this query for instance roughly every 10 seconds, then you can take 2 separate samples (rows) at the log collector side and calculate how much time actually passed between samples, by subtracting the `time` columns between rows.
Then you do the same with the `total_time` columns, and then the formula is simply `CPU% = total_time_diff * 100 / time_diff`.

This might be a bit imprecise because the samples might not always be 10 seconds apart, and so the percentages might not be always fully comparable.

**Comment by sourabhsrawat** [comment]
Great, Thanks!
