### ISSUE TITLE
Intentional Fallthrough?

### ISSUE THREAD

**Issue by r-barnes** [osquery/osquery#8357]
# Bug report

Is [this fallthrough](https://github.com/osquery/osquery/blob/989f37658d0fd142afde2f9945715c14d5889680/osquery/sql/sqlite_encoding.cpp#L49) from `B64_ENCODE_CONDITIONAL` into `B64_ENCODE` intentional?

If so, can we mark it with `__attribute__((fallthrough));` to facilitate enabling `-Wimplicit-fallthrough`?

### What operating system and version are you using?

source code question

### What version of osquery are you using?

master

**Comment by Smjert** [comment]
Hello @r-barnes, I would say it is intentional; the `conditional_to_base64` is documented here: https://osquery.readthedocs.io/en/latest/introduction/sql/#encoding-functions, and so it encodes to base64 only if the character is not printable (ASCII).

I think annotating it with fallthrough is sensible, I would use though the standard notation `[[fallthrough]]`, which should be available since we are compiling with C++17 as the standard.
