### ISSUE TITLE
Explicitly include appropriate std lib headers where using std::vector and std::array

### ISSUE THREAD

**Issue by ilyakurdyukov** [osquery/osquery#8360]
I don't know what std you used that includes them in the basic headers.

`#include <vector>` must be here:

osquery/utils/system/posix/system.cpp
osquery/core/sql/query_performance.cpp
osquery/numeric_monitoring/pre_aggregation_cache.cpp

`#include <array>` must be here:

osquery/worker/ipc/posix/pipe_channel_factory.h

**Comment by ilyakurdyukov** [comment]
Problem building osquery. With Clang 18.1.8, but the includes may be from GCC 13, I don’t know. Doesn't matter, this is clearly a problem with osquery sources.

Does the linter use a specific set of includes from a specific compiler? If yes, then this is very bad. The linter must not scan ANY system header and draw conclusions from its contents.

**Comment by Smjert** [comment]
> Problem building osquery. With Clang 18.1.8, but the includes may be from GCC 13, I don’t know. Doesn't matter, this is clearly a problem with osquery sources.
> 
> Does the linter use a specific set of includes from a specific compiler? If yes, then this is very bad. The linter must not scan ANY system header and draw conclusions from its contents.

We don't use any linter and the code compiles on the CI with Clang 9.0.0 (custom toolchain) on Linux, Clang 15 (Apple version) and Visual Studio 2022.
But sometimes compilers change what they include internally in the system headers and so missing headers in our code are surfaced.

The only tool I know is Include What You Use (https://github.com/include-what-you-use/include-what-you-use), but while it can be useful, it's not something to base a CI check on, since it's not always correct and as the descriptions says it makes assumptions, expecting a codebase organized a Google does internally.
Moreover it would work only for Linux builds.

That being said, the compilers I've listed above are the ones the project officially supports building osquery with, but we are open to corrections to headers like this via PR, since they won't impact the build with the current compilers.

**Comment by ilyakurdyukov** [comment]
I don't want to bother with your CLA bureaucracy, so I'll close PR. Fix it yourself or don’t fix it, I don't care.
